from dataclasses import dataclass, field
from datetime import datetime
from typing import Protocol
from uuid import UUID

from server.app.identity.domain import Principal, SessionKind


@dataclass(frozen=True)
class PublicUser:
    user_id: UUID
    display_name: str


@dataclass(frozen=True)
class QqIdentity:
    client_id: str
    openid: str
    profile: dict = field(default_factory=dict)


class QqProviderError(RuntimeError):
    """Sanitized provider failure; never attach response bodies or request URLs."""


class QqGateway(Protocol):
    def authorization_url(self, state: str) -> str: ...
    def exchange_code(self, code: str) -> QqIdentity: ...


class QqIdentityRepository(Protocol):
    def insert_qq_login_attempt(self, *, state_hash: str, browser_hash: str, expires_at: datetime, now: datetime) -> None: ...
    def consume_qq_login_attempt(self, *, state_hash: str, browser_hash: str, now: datetime) -> bool: ...
    def upsert_qq_identity(self, *, appid: str, openid: str, profile: dict, now: datetime) -> UUID: ...
    def has_qq_identity(self, *, user_id: UUID, appid: str) -> bool: ...
    def get_qq_profile(self, *, user_id: UUID, appid: str) -> dict: ...
    def issue_auth_session(self, *, token_hash: str, user_id: UUID, kind: SessionKind, expires_at: datetime) -> None: ...
    def resolve_auth_session(self, *, token_hash: str, kind: SessionKind, now: datetime) -> Principal | None: ...
    def revoke_auth_session(self, *, token_hash: str, kind: SessionKind, now: datetime) -> None: ...
    def get_public_user(self, user_id: UUID) -> PublicUser | None: ...
    def get_avatar(self, user_id: UUID) -> str | None: ...
    def ensure_test_user(self, *, user_id: UUID, display_name: str, now: datetime) -> None: ...
