const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')

function block(css, selector) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = css.match(new RegExp(`${escaped}\\s*\\{([\\s\\S]*?)\\}`))
  assert.ok(match, `${selector} block should exist`)
  return match[1]
}

function readNewsFiles() {
  const appCss = fs.readFileSync('app.wxss', 'utf8')
  const pageWxml = fs.readFileSync('pages/news/news.wxml', 'utf8')
  const channelWxml = fs.readFileSync('components/channel-dock/channel-dock.wxml', 'utf8')
  const rankedWxml = fs.readFileSync('components/ranked-feed/ranked-feed.wxml', 'utf8')
  const pageCss = fs.readFileSync('pages/news/news.wxss', 'utf8')
  const channelCss = fs.readFileSync('components/channel-dock/channel-dock.wxss', 'utf8')
  const rankedCss = fs.readFileSync('components/ranked-feed/ranked-feed.wxss', 'utf8')
  return {
    js: fs.readFileSync('pages/news/news.js', 'utf8'),
    json: fs.readFileSync('pages/news/news.json', 'utf8'),
    api: fs.readFileSync('pages/news/news-api.js', 'utf8'),
    pageWxml,
    channelWxml,
    rankedWxml,
    wxml: [pageWxml, channelWxml, rankedWxml].join('\n'),
    pageCss,
    channelCss,
    rankedCss,
    appCss,
    css: [appCss, channelCss, rankedCss, pageCss].join('\n'),
    backend: fs.readFileSync('server/news_backend.py', 'utf8')
  }
}

test('news page keeps the dark WoW app shell and low-semantic material layers', () => {
  const { js, wxml, css } = readNewsFiles()

  assert.match(css, /\.news-shell[\s\S]*background:\s*#060606;/)
  assert.match(css, /\.news-shell[\s\S]*isolation:\s*isolate;/)
  assert.match(wxml, /class="page-shell news-shell pass37-page-frame"/)
  assert.match(wxml, /class="page-content news-content pass37-page-frame__content"/)
  assert.match(wxml, /pass37-wow-panel--channel/)
  assert.match(wxml, /pass37-wow-panel--ranked-feed/)
  assert.match(block(css, '.pass37-wow-panel'), /overflow:\s*hidden;/)
  assert.match(block(css, '.pass37-module-card'), /box-sizing:\s*border-box;/)
  assert.match(css, /\.news-shell::after[\s\S]*border-left:\s*1rpx solid rgba\(248,\s*183,\s*0,\s*0\.16\);/)
  assert.match(css, /--wow-tabbar-space:\s*calc\(164rpx \+ env\(safe-area-inset-bottom\)\);/)
  assert.match(css, /\.news-shell \.news-content[\s\S]*padding:\s*14rpx\s+20rpx\s+var\(--wow-tabbar-space\);[\s\S]*overflow:\s*hidden;/)
  assert.match(js, /deferredVisualsReady:\s*false/)
  assert.match(js, /enableDeferredVisuals\(\)/)
  assert.match(js, /handleNewsScroll\(event\)/)
  assert.match(js, /scrollTop > 96/)
  assert.doesNotMatch(js, /onReady\(\)[\s\S]*setTimeout\(\(\) => this\.enableDeferredVisuals/)
  assert.match(wxml, /bindscroll="handleNewsScroll"/)
  assert.doesNotMatch(wxml, /scroll-y\s+type="list"/)
  assert.doesNotMatch(wxml, /assets\/generated/)
  assert.doesNotMatch(wxml, /class="surface-material news-shell-corner-material"/)
  assert.doesNotMatch(wxml, /class="surface-material news-command-material"/)
  assert.match(wxml, /class="surface-material banner-material-image" src="\{\{item\.bannerFallbackUrl\}\}"/)
  assert.match(wxml, /binderror="handleHeroImageError"/)
  assert.match(js, /handleHeroImageError\(event\)/)
  assert.doesNotMatch(wxml, /banner-atmosphere-material/)
  assert.doesNotMatch(block(css, '.banner-visual-shell'), /news_hero_atmosphere_material\.png/)
  assert.match(wxml, /class="news-tab-dock pass37-module-dock pass37-module-dock--channel"/)
  assert.match(wxml, /class="news-tab-rail"/)
  assert.match(wxml, /class="ranked-feed-root pass37-module-dock pass37-module-dock--ranked-feed"/)
  assert.doesNotMatch(wxml, /class="surface-material ranked-feed-material"/)
  assert.doesNotMatch(wxml, /news-command-trim|channel-dock-trim|ranked-feed-trim|highlight-row-material/)
  assert.ok((wxml.match(/surface-material/g) || []).length <= 11, 'news page should not rebuild material layers per row')
  assert.match(block(css, '.focus-row'), /background:\s*[\s\S]*linear-gradient/)
  assert.doesNotMatch(wxml, /news_full_layout_reference|full_layout_reference/)
  assert.doesNotMatch(wxml, /placeholder|fake|mock/i)
})

test('news intelligence summary stays data-derived without manual refresh controls', () => {
  const { js, wxml, css, api } = readNewsFiles()

  assert.match(js, /buildIntelSummary/)
  assert.match(js, /sourceCount/)
  assert.match(wxml, /\{\{intelSummary\.sourceCount\}\}/)
  assert.match(wxml, /\{\{intelSummary\.focusCount\}\}/)
  assert.match(css, /\.news-command[\s\S]*height:\s*155rpx;/)
  assert.match(wxml, /class="news-command-orbit"/)
  assert.match(wxml, /class="news-command-icon-image" src="\/assets\/user\/intel-command-icon\.png"/)
  assert.doesNotMatch(wxml, /class="news-command-crest"/)
  assert.doesNotMatch(wxml, /class="news-command-symbol">情</)
  assert.doesNotMatch(wxml, /class="news-command-glyph"[\s\S]*news_tab_icon_all_pass36\.png/)
  assert.doesNotMatch(wxml, /command-socket-material/)
  assert.doesNotMatch(wxml, /socket_circle_gold_v2\.png/)
  assert.doesNotMatch(css, /\.news-command-glyph/)
  assert.doesNotMatch(wxml, /class="news-command-scanline"/)
  assert.match(block(css, '.news-command-icon-image'), /width:\s*100%;/)
  assert.match(block(css, '.news-command-icon-image'), /height:\s*100%;/)
  assert.match(block(css, '.news-command-icon-image'), /object-fit:\s*cover;/)
  assert.match(block(css, '.news-command-icon-image'), /transform:\s*translate\(-50%,\s*-50%\);/)
  assert.match(block(css, '.command-socket-material'), /display:\s*none;/)
  assert.match(block(css, '.news-command-crest'), /display:\s*none;/)
  assert.match(block(css, '.news-command-symbol'), /display:\s*none;/)
  assert.match(css, /\.news-command-emblem::before[\s\S]*border:\s*1rpx solid rgba\(248,\s*183,\s*0,\s*0\.22\);/)
  assert.match(css, /\.news-command-crest[\s\S]*border-radius:\s*50%;/)
  assert.match(css, /\.news-command-orbit-dot[\s\S]*box-shadow:\s*0 0 12rpx rgba\(248,\s*183,\s*0,\s*0\.42\);/)
  assert.match(wxml, /class="news-command-chip"/)
  assert.doesNotMatch(js, /requestManualRefresh/)
  assert.doesNotMatch(wxml, /bindtap="handleRefresh"/)
  assert.doesNotMatch(wxml, />刷新</)
  assert.doesNotMatch(api, /mode=manual/)
})

test('news pass36 channel dock is six real tabs, not metric badges', () => {
  const { js, json, pageWxml, channelWxml, wxml, css } = readNewsFiles()
  const dockBlock = block(css, '.news-tab-dock')
  const tabBlock = block(css, '.news-tab-item')
  const orbBlock = block(css, '.news-tab-orb')

  ;['综合', '官方', '更新', '活动', '社区', '攻略'].forEach((label) => {
    assert.match(js, new RegExp(`title:\\s*'${label}'`))
  })
  assert.match(js, /NEWS_TAB_DEFS/)
  assert.match(js, /buildNewsTabs/)
  assert.match(js, /articleMatchesTab/)
  assert.doesNotMatch(js, /news_tab_icon_all_pass36\.png/)
  assert.doesNotMatch(js, /news_tab_icon_official_pass36\.png/)
  assert.doesNotMatch(js, /NEWS_TAB_ICON_BY_KEY/)
  assert.doesNotMatch(channelWxml, /<image[\s\S]*item\.iconUrl/)
  assert.match(json, /"channel-dock":\s*"\/components\/channel-dock\/channel-dock"/)
  assert.match(pageWxml, /<channel-dock[\s\S]*items="\{\{newsTabs\}\}"[\s\S]*bind:tabtap="openNewsTab"/)
  assert.match(channelWxml, /wx:for="\{\{items\}\}"/)
  assert.match(channelWxml, /bindtap="handleTabTap"/)
  assert.match(wxml, /class="news-tab-cell-surface"/)
  assert.match(wxml, /pass37-module-dock--channel/)
  assert.match(wxml, /news-tab-item pass37-module-card/)
  assert.match(wxml, /class="news-tab-rail"/)
  assert.match(wxml, /class="news-tab-icon-slot"/)
  assert.match(wxml, /class="news-tab-label-slot"/)
  assert.match(wxml, /class="news-tab-active-mark"/)
  assert.match(wxml, /class="news-tab-title"/)
  assert.match(wxml, /class="news-tab-icon"/)
  assert.match(dockBlock, /grid-template-columns:\s*repeat\(6,\s*minmax\(0,\s*1fr\)\);/)
  assert.match(dockBlock, /height:\s*100%;/)
  assert.match(tabBlock, /grid-template-rows:\s*58rpx\s+32rpx;/)
  assert.match(tabBlock, /min-height:\s*0;/)
  assert.match(tabBlock, /height:\s*100%;/)
  assert.match(orbBlock, /width:\s*50rpx;/)
  assert.match(orbBlock, /align-items:\s*center;/)
  assert.match(orbBlock, /justify-content:\s*center;/)
  assert.match(orbBlock, /rgba\(248,\s*183,\s*0,\s*0\.28\)/)
  assert.match(block(css, '.news-tab-icon-slot'), /width:\s*58rpx;/)
  assert.match(block(css, '.news-tab-icon-slot'), /height:\s*58rpx;/)
  assert.match(block(css, '.news-tab-icon'), /width:\s*50rpx;/)
  assert.match(block(css, '.news-tab-icon'), /height:\s*50rpx;/)
  assert.match(block(css, '.news-tab-icon'), /line-height:\s*50rpx;/)
  assert.match(block(css, '.news-tab-icon'), /text-align:\s*center;/)
  assert.doesNotMatch(css, /visual-key-all \.news-tab-icon[\s\S]*translate/)
  assert.doesNotMatch(css, /visual-key-official \.news-tab-icon[\s\S]*translate/)
  assert.match(block(css, '.news-tab-label-slot'), /min-height:\s*32rpx;/)
  assert.match(block(css, '.news-tab-label-slot'), /height:\s*32rpx;/)
  assert.match(block(css, '.news-channel-section'), /height:\s*154rpx;/)
  assert.match(block(css, '.news-channel-section'), /width:\s*100%;/)
  assert.match(block(css, '.news-channel-section'), /max-width:\s*100%;/)
  assert.match(block(css, '.news-tab-rail'), /left:\s*7rpx;/)
  assert.match(block(css, '.news-tab-rail'), /border-radius:\s*7rpx;/)
  assert.match(block(css, '.news-tab-item::after'), /border-radius:\s*44rpx\s+44rpx\s+5rpx\s+5rpx;/)
  assert.match(block(css, '.news-tab-item::after'), /inset 0 -8rpx 12rpx rgba\(0,\s*0,\s*0,\s*0\.16\)/)
  assert.match(block(css, '.news-tab-item.is-active::after'), /border-color:\s*rgba\(248,\s*183,\s*0,\s*0\.16\);/)
  assert.match(block(css, '.news-tab-item.is-active .news-tab-title'), /color:\s*#f8d776;/)
  assert.match(block(css, '.news-tab-cell-surface'), /display:\s*none;/)
  assert.match(block(css, '.news-tab-cell-surface'), /border-radius:\s*50%;/)
  assert.match(block(css, '.news-tab-cell-surface'), /width:\s*58rpx;/)
  assert.match(block(css, '.news-tab-cell-surface'), /height:\s*58rpx;/)
  assert.match(block(css, '.news-tab-cell-surface'), /border:\s*0;/)
  assert.doesNotMatch(block(css, '.news-tab-cell-surface'), /margin-left:/)
  assert.doesNotMatch(block(css, '.news-tab-cell-surface'), /inset:\s*3rpx\s+2rpx\s+2rpx/)
  assert.doesNotMatch(block(css, '.news-tab-label-slot'), /border-top:/)

  assert.doesNotMatch(wxml, /wx:for="\{\{channelDockItems\}\}"/)
  assert.doesNotMatch(wxml, /class="channel-count-badge"/)
  assert.doesNotMatch(css, /\.channel-count-badge/)
  assert.doesNotMatch(wxml, /今日重点<\/text>[\s\S]*更新总量<\/text>[\s\S]*来源覆盖<\/text>/)
})

test('news pass36 tab navigation has compatible real filters', () => {
  const { js, api, backend } = readNewsFiles()

  ;['official', 'updates', 'events', 'community', 'guides'].forEach((key) => {
    assert.match(js, new RegExp(`key:\\s*'${key}'`))
    assert.match(api, new RegExp(`key === '${key}'`))
    assert.match(backend, new RegExp(`key == "${key}"`))
  })
  assert.match(api, /filterFallbackByMetricKey/)
  assert.match(backend, /def article_search_text/)
})

test('news pass36 focus list is a five-row compact feed', () => {
  const { js, json, pageWxml, rankedWxml, wxml, css } = readNewsFiles()
  const feedBlock = block(css, '.news-feed-section')
  const rowBlock = block(css, '.focus-row')
  const thumbBlock = block(css, '.focus-thumb')
  const titleBlock = block(css, '.focus-title')

  assert.match(js, /rankedHighlights/)
  assert.match(js, /RANKED_FOCUS_COUNT\s*=\s*5/)
  assert.match(js, /buildRankedHighlights/)
  assert.match(js, /sourceReferenceHighlights/)
  assert.match(js, /evidenceGapRow/)
  assert.match(js, /normalizeRankedHighlight/)
  assert.match(js, /compactRankedTitle/)
  assert.doesNotMatch(js, /const metaParts = \[\s*formatRelativeShort\(source\.publishedAt\),\s*compactSourceName/)
  assert.match(js, /const metaParts = \[\s*formatRelativeShort\(source\.publishedAt\),\s*visualSourceLabelForArticle\(source\)\s*\]/)
  assert.match(js, /不伪造资讯/)
  assert.doesNotMatch(js, /assets\/generated/)
  assert.match(js, /source_reference:\s*'\/assets\/tabbar\/news-selected\.png'/)
  assert.match(js, /official:\s*'\/assets\/tabbar\/builds-selected\.png'/)
  assert.match(js, /来源参考待核验 \/ 不计入推荐/)
  assert.match(js, /版本线索缺少可公开来源，暂不生成标题或结论/)
  assert.match(js, /fallbackThumbUrl:\s*NEWS_FALLBACK_THUMB_BY_KEY\.source_reference/)
  assert.match(js, /rowState:\s*isEvidenceGap \? 'source_reference' : 'published'/)
  assert.match(js, /thumbState:\s*visualUrl \? 'article_image' : \(fallbackThumbUrl \? 'fallback_thumb' : 'glyph'\)/)
  assert.match(js, /isOpenable:\s*!isEvidenceGap && !!item\.id/)
  assert.match(js, /displayFeedMeta/)
  assert.match(js, /displayRankedTitle/)
  assert.match(json, /"ranked-feed":\s*"\/components\/ranked-feed\/ranked-feed"/)
  assert.match(pageWxml, /<ranked-feed[\s\S]*id="rankedFeed"[\s\S]*class="news-ranked-feed-component"/)
  assert.match(pageWxml, /<ranked-feed[\s\S]*items="\{\{rankedHighlights\}\}"[\s\S]*bind:itemtap="openArticle"[\s\S]*bind:actiontap="openNewsTab"/)
  assert.match(rankedWxml, /wx:for="\{\{items\}\}"/)
  assert.match(wxml, /item\.isOpenable \? item\.id : ''/)
  assert.match(wxml, /data-row-state="\{\{item\.rowState\}\}"/)
  assert.match(wxml, /data-thumb-state="\{\{item\.thumbState\}\}"/)
  assert.match(wxml, /state-\{\{item\.rowState\}\}/)
  assert.match(wxml, /thumb-\{\{item\.thumbState\}\}/)
  assert.match(wxml, /isOpenable \? '' : 'is-disabled-row'/)
  assert.match(wxml, /index == 4 \? 'is-final-focus-row' : ''/)
  assert.match(wxml, /class="focus-row pass37-module-card visual-tone-\{\{item\.visualTone\}\}/)
  assert.match(wxml, /ranked-feed-root pass37-module-dock pass37-module-dock--ranked-feed/)
  assert.match(wxml, /class="focus-rank-number"/)
  assert.match(wxml, /class="focus-thumb thumb-state-\{\{item\.thumbState\}\}"/)
  assert.match(wxml, /class="focus-badge"/)
  assert.match(wxml, /\{\{item\.displayRankedTitle \|\| item\.title\}\}/)
  assert.match(wxml, /class="focus-title"/)
  assert.match(wxml, /class="focus-meta"/)
  assert.match(wxml, /class="focus-save-mark"/)
  assert.match(feedBlock, /height:\s*717rpx;/)
  assert.match(feedBlock, /min-height:\s*717rpx;/)
  assert.match(block(css, '.news-feed-section'), /padding:\s*16rpx\s+15rpx\s+18rpx;/)
  assert.match(block(css, '.ranked-feed-header'), /margin-bottom:\s*13rpx;/)
  assert.match(block(css, '.ranked-feed-header::after'), /left:\s*138rpx;/)
  assert.match(block(css, '.ranked-feed-header::after'), /right:\s*70rpx;/)
  assert.match(block(css, '.focus-list'), /gap:\s*7rpx;/)
  assert.match(block(css, '.focus-head'), /overflow:\s*hidden;/)
  assert.match(rowBlock, /grid-template-columns:\s*52rpx\s+116rpx\s+minmax\(0,\s*1fr\)\s+32rpx;/)
  assert.match(rowBlock, /gap:\s*8rpx;/)
  assert.match(rowBlock, /height:\s*116rpx;/)
  assert.match(rowBlock, /border-radius:\s*6rpx;/)
  assert.doesNotMatch(rowBlock, /news_rank_row_material\.png/)
  assert.match(thumbBlock, /width:\s*116rpx;/)
  assert.match(thumbBlock, /height:\s*96rpx;/)
  assert.match(block(css, '.focus-rank-number'), /font-size:\s*34rpx;/)
  assert.match(block(css, '.focus-save-mark'), /width:\s*17rpx;/)
  assert.match(block(css, '.focus-save-mark'), /height:\s*27rpx;/)
  assert.match(block(css, '.focus-row:nth-child(1)'), /border-color:\s*rgba\(248,\s*183,\s*0,\s*0\.18\);/)
  assert.match(block(css, '.focus-row:nth-child(1) .focus-rank-number'), /color:\s*#f8b700;/)
  assert.match(css, /\.focus-row\.visual-tone-update \.focus-badge,[\s\S]*color:\s*#8bd8ff;/)
  assert.match(css, /\.focus-row\.visual-tone-event \.focus-badge[\s\S]*color:\s*#9cdf8b;/)
  assert.match(css, /\.focus-row\.visual-tone-guide \.focus-badge[\s\S]*color:\s*#ffbf64;/)
  assert.match(css, /\.focus-row\.visual-tone-community \.focus-badge[\s\S]*color:\s*#93b9ff;/)
  assert.match(block(css, '.focus-row.is-evidence-gap'), /border-color:\s*rgba\(84,\s*192,\s*255,\s*0\.08\);/)
  assert.match(block(css, '.focus-row.state-source_reference'), /border-color:\s*rgba\(84,\s*192,\s*255,\s*0\.1\);/)
  assert.match(block(css, '.focus-row.state-source_reference .focus-thumb'), /border-color:\s*rgba\(84,\s*192,\s*255,\s*0\.16\);/)
  assert.match(block(css, '.focus-thumb.thumb-state-fallback_thumb .focus-thumb-fallback-image'), /opacity:\s*0\.96;/)
  assert.match(block(css, '.focus-row.is-final-focus-row'), /rgba\(84,\s*192,\s*255,\s*0\.06\)/)
  assert.match(block(css, '.focus-save.is-disabled'), /opacity:\s*0\.42;/)
  assert.match(titleBlock, /font-size:\s*23rpx;/)
  assert.match(titleBlock, /min-width:\s*0;/)
  assert.match(titleBlock, /white-space:\s*nowrap;/)
  assert.match(block(css, '.focus-badge'), /max-width:\s*74rpx;/)
  assert.match(css, /(^|\n)\.focus-channel\s*\{[\s\S]*display:\s*none;/)
  assert.match(block(css, '.focus-meta-row'), /overflow:\s*hidden;/)
  assert.match(block(css, '.focus-meta'), /font-size:\s*18rpx;/)
  assert.match(css, /@media \(max-width:\s*380px\)[\s\S]*\.focus-row[\s\S]*grid-template-columns:\s*44rpx\s+104rpx\s+minmax\(0,\s*1fr\)\s+28rpx;/)
  assert.doesNotMatch(titleBlock, /-webkit-line-clamp:\s*2;/)

  assert.doesNotMatch(wxml, /class="highlight-card"/)
  assert.doesNotMatch(wxml, /class="highlight-action">查看</)
  assert.doesNotMatch(wxml, /class="highlight-summary"/)
})

test('news visual slots use article images first and truthful fallback metadata second', () => {
  const { js, wxml, css } = readNewsFiles()

  assert.match(js, /visualUrlForArticle/)
  assert.match(js, /visualTextForArticle/)
  assert.match(js, /event\|trading-post\|weekly\|rewards\|活动\|商栈\|周报\|奖励\|timeways/)
  assert.match(js, /guide\|攻略\|指南\|how to\|玩法\|build\|rotation\|simc\|wcl/)
  assert.match(js, /fallbackThumbUrlForArticle/)
  assert.doesNotMatch(js, /fallbackIconUrlForArticle/)
  assert.doesNotMatch(wxml, /class="visual-glyph-thumb"[\s\S]*fallbackIconUrl/)
  assert.match(js, /fallbackCategoryKeyForArticle/)
  assert.match(js, /fallbackTabKeyForArticle/)
  assert.match(js, /NEWS_FALLBACK_TAB_KEY_BY_CATEGORY/)
  assert.match(js, /function buildHeroNews\(payload\)/)
  assert.match(js, /heroNews:\s*buildHeroNews\(source\)/)
  assert.doesNotMatch(js, /visualSourceMarkForArticle|visualSourceMark/)
  assert.doesNotMatch(js, /news_thumb_fallback_/)
  assert.doesNotMatch(js, /assets\/generated/)
  assert.match(js, /\/ptr\|beta\|测试服\|测试\/\.test\(text\)/)
  assert.match(js, /\/content-update\|patch\|更新\|补丁\|内容更新\/\.test\(text\)/)
  assert.match(js, /\/raid\|团本\|团队\|dungeon\|地下城\/\.test\(text\)/)
  assert.match(wxml, /wx:if="\{\{item\.visualUrl && !item\.visualBroken\}\}"/)
  assert.match(wxml, /src="\{\{item\.bannerFallbackUrl\}\}"/)
  assert.doesNotMatch(wxml, /wx:if="\{\{!item\.visualUrl \|\| item\.visualBroken\}\}" class="surface-material banner-material-image"/)
  assert.match(wxml, /wx:if="\{\{item\.fallbackThumbUrl\}\}"/)
  assert.match(wxml, /class="focus-thumb-fallback-image"/)
  assert.match(wxml, /class="focus-thumb-fallback visual-tone-\{\{item\.visualTone\}\}"/)
  assert.doesNotMatch(wxml, /highlight-socket-material/)
  assert.doesNotMatch(wxml, /class="visual-glyph-thumb"/)
  assert.doesNotMatch(wxml, /visual-source-badge|visualSourceMark/)
  assert.match(wxml, /\{\{item\.displayFeedMeta\}\}/)
  assert.doesNotMatch(wxml, /class="visual-source-label"/)
  assert.match(css, /\.focus-thumb > image/)
  assert.match(block(css, '.banner-material-image'), /z-index:\s*0;/)
  assert.match(block(css, '.banner-visual-image'), /z-index:\s*1;/)
  assert.match(css, /\.focus-thumb-fallback-image[\s\S]*opacity:\s*0\.92;/)
  assert.doesNotMatch(css, /\.visual-glyph-thumb/)
  assert.match(css, /\.focus-thumb-fallback\.visual-tone-ptr/)
  assert.doesNotMatch(css, /\.visual-source-badge/)
  assert.doesNotMatch(wxml, /阅读量|万阅读|综合评分|提升优先级|S 级|DPS/)
})
