// Cloud-only isolated Candidate. Session values and player source never enter output.
const {chromium} = require('/opt/chickenbro-candidates/poe2-20260918/runtime/browser/node_modules/playwright')
const fs = require('node:fs'), assert = require('node:assert/strict')
const root = '/opt/chickenbro-candidates/poe2-20260918', origin = 'https://www.chickenbro.cloud'
async function main() {
  const session = JSON.parse(fs.readFileSync(root + '/runtime/browser/passive-tree-sessions.json', 'utf8')).A
  const api = JSON.parse(fs.readFileSync(root + '/evidence/passive-tree/api.json', 'utf8'))
  const browser = await chromium.launch({headless: true, executablePath: root + '/runtime/browser/chrome-headless-shell-linux64/chrome-headless-shell', args: ['--no-sandbox']})
  const context = await browser.newContext({viewport: {width: 1440, height: 1000}})
  await context.addCookies([{name: '__Host-chickenbro-poe2-candidate-session', value: session.token, url: origin, httpOnly: true, secure: true, sameSite: 'Lax'}, {name: '__Host-chickenbro-poe2-candidate-csrf', value: session.csrf, url: origin, secure: true, sameSite: 'Lax'}])
  const page = await context.newPage(), errors = [], checks = []
  page.on('pageerror', error => errors.push(error.name))
  try {
    await page.goto(origin + '/poe2-candidate/poe2', {waitUntil: 'domcontentloaded'})
    await page.getByRole('heading', {name: '我的构筑', exact: true}).waitFor()
    const builds = await (await context.request.get(origin + '/poe2-candidate/api/v2/poe2/builds')).json()
    const index = builds.items.findIndex(b => b.id === api.buildId); assert.ok(index >= 0)
    const response = page.waitForResponse(r => r.url().endsWith('/builds/' + api.buildId + '/tree') && r.status() === 200, {timeout: 90000})
    await page.locator('aside button[data-active]').nth(index).click()
    const tree = await (await response).json()
    const panel = page.getByRole('region', {name: '构筑天赋树', exact: true})
    await panel.locator('canvas').waitFor()
    await page.waitForFunction(() => document.querySelector('[data-tree-nodes]')?.getAttribute('data-art-ready') === 'true', {timeout: 30000})
    assert.equal(Number(await panel.getAttribute('data-tree-nodes')), tree.nodes.length)
    const canvas = panel.locator('canvas')
    assert.ok((await panel.innerText()).includes('原始构筑的天赋分配'))
    await panel.screenshot({path: root + '/evidence/passive-tree/tree-desktop.png'})
    const before = await canvas.evaluate(el => el.toDataURL())
    await page.getByRole('button', {name: '放大天赋树', exact: true}).click()
    assert.notEqual(await canvas.evaluate(el => el.toDataURL()), before)
    const box = await canvas.boundingBox()
    await page.mouse.move(box.x + 180, box.y + 180); await page.mouse.down(); await page.mouse.move(box.x + 240, box.y + 210, {steps: 5}); await page.mouse.up()
    assert.notEqual(await canvas.evaluate(el => el.toDataURL()), before)
    await page.getByRole('button', {name: '查看全树', exact: true}).click()
    await page.getByRole('button', {name: '定位已点', exact: true}).click()
    checks.push('real main tree, matching node count, atlas loaded, zoom/pan/fit')
    const asc = tree.nodes.find(n => n.allocated && n.ascendancy === tree.ascendancy && n.type === 'Notable')
    assert.ok(asc)
    await page.getByRole('button', {name: /^升华 ·/}).first().click()
    await panel.getByRole('button', {name: new RegExp('#' + asc.id + '$')}).click()
    const detail = page.getByRole('complementary', {name: '节点详情', exact: true})
    assert.ok((await detail.innerText()).includes(asc.name))
    for (const stat of asc.stats) assert.ok((await detail.innerText()).includes(stat))
    await panel.screenshot({path: root + '/evidence/passive-tree/ascendancy-desktop.png'})
    await page.getByRole('button', {name: '天赋树', exact: true}).click()
    const main = tree.nodes.find(n => n.allocated && !n.ascendancy && n.type === 'Notable')
    await page.getByRole('textbox', {name: '搜索天赋节点', exact: true}).fill(String(main.id))
    await panel.getByRole('button', {name: new RegExp('#' + main.id + '$')}).click()
    assert.ok((await detail.innerText()).includes(main.name))
    await page.getByRole('combobox', {name: '天赋武器组', exact: true}).selectOption('1')
    await page.getByRole('combobox', {name: '天赋武器组', exact: true}).selectOption('2')
    checks.push('current ascendancy, exact node stats, search and focus, weapon selectors')
    await page.setViewportSize({width: 390, height: 844})
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 2))
    await panel.screenshot({path: root + '/evidence/passive-tree/tree-mobile.png'})
    await page.getByRole('button', {name: /^升华 ·/}).first().click()
    await page.getByRole('button', {name: '查看全树', exact: true}).click()
    await panel.screenshot({path: root + '/evidence/passive-tree/ascendancy-mobile.png'})
    checks.push('390px no overflow, main and ascendancy views')
    await page.setViewportSize({width: 1440, height: 1000})
    const jobResponse = page.waitForResponse(r => r.url().includes('/tree?jobId=' + api.jobId) && r.status() === 200, {timeout: 90000})
    await page.getByRole('button', {name: '③ 查看详情', exact: true}).click()
    const jobTree = await (await jobResponse).json()
    await panel.locator('canvas').waitFor()
    assert.ok((await panel.innerText()).includes('当前计算结果的天赋分配'))
    assert.equal(jobTree.nodes.filter(n => n.allocated).length, api.resultAllocated)
    checks.push('result detail renders actual changed job tree')
    assert.deepEqual(errors, [])
    fs.writeFileSync(root + '/evidence/passive-tree/browser.json', JSON.stringify({passed: true, checks, errors, nodes: tree.nodes.length}, null, 2))
    console.log(JSON.stringify({passed: true, checks}))
  } finally {await browser.close()}
}
main().catch(error => {console.error(error.name + ': ' + error.message.replace(/https?:\/\/\S+/g, '[URL]')); process.exitCode = 1})
