// Cloud-only live Task6. Screenshots mask all URL/source inputs; no raw payload logs.
const {chromium}=require('/opt/chickenbro-candidates/poe2-20260918/runtime/browser/node_modules/playwright')
const fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto')
const root='/opt/chickenbro-candidates/poe2-20260918', out=root+'/evidence/task6',origin='https://www.chickenbro.cloud',prefix=origin+'/poe2-candidate/api/v2'
const sessions=JSON.parse(fs.readFileSync(root+'/runtime/browser/session-fixtures.json','utf8'))
const ninja='https://poe.ninja/poe2/profile/wuba-4006/forbiddenrites/character/玩個那個破大錘'
const checks=[],errors=[],responses=[]
async function main(){
 const browser=await chromium.launch({headless:true,executablePath:root+'/runtime/browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']})
 const context=await browser.newContext({viewport:{width:1440,height:1000}})
 await context.addCookies([{name:'__Host-chickenbro-poe2-candidate-session',value:sessions.A.token,url:origin,httpOnly:true,secure:true,sameSite:'Lax'},{name:'__Host-chickenbro-poe2-candidate-csrf',value:sessions.A.csrf,url:origin,secure:true,sameSite:'Lax'}])
 const page=await context.newPage()
 page.on('pageerror',()=>errors.push('pageerror'))
 page.on('response',r=>{if(r.request().method()==='POST'&&r.url().startsWith(prefix+'/poe2/'))responses.push({path:new URL(r.url()).pathname,status:r.status()})})
 async function shot(name){await page.screenshot({path:out+'/'+name+'.png',fullPage:true,mask:[page.locator('input'),page.locator('textarea')]})}
 async function api(path){const r=await context.request.get(prefix+path);assert.equal(r.status(),200);return r.json()}
 try{
 await page.goto(origin+'/poe2-candidate/poe2',{waitUntil:'domcontentloaded'})
 await page.getByRole('button',{name:'① 导入构筑',exact:true}).waitFor()
 await page.getByLabel('角色链接',{exact:true}).fill(ninja)
 assert.ok(await page.getByRole('button',{name:'读取角色',exact:true}).isDisabled())
 await page.getByRole('button',{name:'国际服 · poe.ninja',exact:true}).click()
 await page.getByLabel('角色链接',{exact:true}).fill('https://www.wegame.com.cn/helper/poe2/#/share/fixture')
 assert.ok(await page.getByRole('button',{name:'读取角色',exact:true}).isDisabled())
 checks.push('both provider mismatch inputs disabled')
 const wid=fs.readFileSync(out+'/wegame-id.txt','utf8').trim(), storageKey='poe2-import:'+crypto.createHash('sha256').update(sessions.A.csrf).digest('hex')
 await page.evaluate(({storageKey,wid})=>sessionStorage.setItem(storageKey,wid),{storageKey,wid})
 await page.reload({waitUntil:'domcontentloaded'})
 await page.getByRole('heading',{name:'已取消导入',exact:true}).waitFor()
 await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('heading',{name:'已取消导入',exact:true}).waitFor()
 checks.push('cancelled task survives reload')
 await page.getByRole('button',{name:'国际服 · poe.ninja',exact:true}).click()
 await page.getByLabel('角色链接',{exact:true}).fill(ninja)
 await page.getByRole('button',{name:'读取角色',exact:true}).click()
 await page.getByRole('heading',{name:'需要补充完整 PoB 构筑',exact:true}).waitFor()
 const id=await page.evaluate(key=>sessionStorage.getItem(key),storageKey)
 const np=await api('/poe2/imports/'+id);assert.equal(np.status,'needs_input')
 const anchor=page.getByRole('link',{name:'打开 poe.ninja 角色页',exact:true});assert.equal(decodeURI(await anchor.getAttribute('href')),ninja)
 assert.equal(await anchor.getAttribute('target'),'_blank');assert.ok((await anchor.getAttribute('rel')).includes('noopener'))
 await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('heading',{name:'需要补充完整 PoB 构筑',exact:true}).waitFor()
 assert.equal(decodeURI(await anchor.getAttribute('href')),ninja)
 checks.push('actual user ninja URL safe original-page link survives refresh')
 await page.setViewportSize({width:390,height:844})
 await page.getByLabel('补充 PoB',{exact:true}).fill(fs.readFileSync(root+'/evidence/link-research/ninja-build.xml','utf8'))
 assert.ok(await page.getByRole('button',{name:'补充并计算基线',exact:true}).isDisabled())
 await page.getByRole('checkbox',{name:/我确认使用这份构筑/}).check()
 await page.getByRole('button',{name:'补充并计算基线',exact:true}).click()
 await page.getByRole('heading',{name:'第二步 · 调整与对比',exact:true}).waitFor({timeout:120000})
 const ready=await api('/poe2/imports/'+id);assert.equal(ready.status,'ready')
 const job=await api('/poe2/jobs/'+ready.baselineJobId);assert.equal(job.status,'succeeded')
 for(const [k,v] of Object.entries({Life:2813,EnergyShield:962,Armour:7284,Evasion:14138}))assert.equal(job.result.stats[k],v,k)
 assert.equal(responses.filter(r=>r.path.endsWith('/poe2/jobs')).length,0)
 assert.ok(!(await page.getByRole('button',{name:'计算方案',exact:true}).isDisabled()))
 await shot('ninja-ready-mobile')
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+4))
 await page.setViewportSize({width:1440,height:1000});await shot('ninja-ready-desktop')
 checks.push('ninja user confirmation, real XML ready, exact defensive stats, baseline reused without job POST')
 await page.getByRole('button',{name:'查看完整详情 →',exact:true}).click()
 await page.getByRole('heading',{name:'第三步 · 查看详情',exact:true}).waitFor()
 await page.getByRole('button',{name:'导出此方案',exact:true}).click()
 assert.ok((await page.getByLabel('导出的构筑').inputValue()).length>100)
 await shot('details-export-masked');checks.push('step3 detail and real export')
 await page.getByRole('button',{name:'① 导入构筑',exact:true}).click()
 await page.getByLabel('角色链接',{exact:true}).waitFor()
 assert.equal(await page.evaluate(key=>sessionStorage.getItem(key),storageKey),null)
 await page.getByRole('button',{name:'国际服 · poe.ninja',exact:true}).click()
 await page.getByLabel('角色链接',{exact:true}).fill(ninja)
 await page.getByRole('button',{name:'读取角色',exact:true}).click()
 await page.getByRole('heading',{name:'需要补充完整 PoB 构筑',exact:true}).waitFor()
 const nextId=await page.evaluate(key=>sessionStorage.getItem(key),storageKey);assert.notEqual(nextId,id)
 await page.getByRole('button',{name:'取消导入',exact:true}).click()
 await page.getByRole('heading',{name:'已取消导入',exact:true}).waitFor()
 checks.push('ready returns to step1 and creates a distinct next import')
 await page.getByText('已有 PoB 构筑 · 手动导入与教学示例',{exact:true}).click()
 await page.getByRole('button',{name:'使用示例构筑',exact:true}).click()
 await page.getByRole('heading',{name:'第二步 · 调整与对比',exact:true}).waitFor({timeout:70000})
 checks.push('example import compatibility')
 await page.getByRole('button',{name:'① 导入构筑',exact:true}).click()
 const manual=page.getByText('已有 PoB 构筑 · 手动导入与教学示例',{exact:true});if(!await page.getByLabel('构筑分享码',{exact:true}).isVisible())await manual.click()
 await page.getByLabel('构筑分享码',{exact:true}).fill(fs.readFileSync(root+'/evidence/fixtures/build-1.xml','utf8'))
 await page.getByRole('button',{name:'导入构筑',exact:true}).click()
 await page.getByRole('heading',{name:'第二步 · 调整与对比',exact:true}).waitFor({timeout:70000})
 checks.push('manual XML import compatibility')
 await page.getByLabel('选择游戏').selectOption('wow');await page.locator('[aria-label="SimC 模拟"]').click();assert.ok(page.url().includes('/simc'));checks.push('WoW SimC navigation')
 const other=await browser.newContext();await other.addCookies([{name:'__Host-chickenbro-poe2-candidate-session',value:sessions.B.token,url:origin,httpOnly:true,secure:true},{name:'__Host-chickenbro-poe2-candidate-csrf',value:sessions.B.csrf,url:origin,secure:true}])
 for(const path of ['/poe2/imports/'+id,'/poe2/builds/'+ready.buildId,'/poe2/jobs/'+ready.baselineJobId])assert.equal((await other.request.get(prefix+path)).status(),404)
 assert.equal((await other.request.post(prefix+'/poe2/imports/'+id+'/retry',{headers:{'X-CSRF-Token':sessions.B.csrf,Origin:origin},data:{idempotencyKey:crypto.randomUUID()}})).status(),404)
 checks.push('B real cookies cannot read A import/build/baseline')
 assert.deepEqual(errors,[])
 fs.writeFileSync(out+'/browser.json',JSON.stringify({passed:true,checks,errors,responses,ninja:{id,buildId:ready.buildId,baselineJobId:ready.baselineJobId,stats:job.result.stats,engineVersion:job.result.engineVersion},screenshots:'inputs and textareas masked; no source payload captured'},null,2))
 console.log(JSON.stringify({passed:true,checks}))
 }catch(e){await shot('failure-masked');fs.writeFileSync(out+'/browser-failure.json',JSON.stringify({passed:false,checks,error:String(e).replace(/https?:\/\/[^\s]+/g,'[URL]'),errors},null,2));console.error('Task6 browser failed after '+checks.length+' checks; sanitized failure JSON saved');process.exitCode=1}finally{await browser.close()}
}
main().catch(()=>{console.error('Task6 browser launch failed');process.exitCode=1})
