const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')

test('profile page exposes WeChat avatar and nickname profile bindings', () => {
  const js = fs.readFileSync('pages/profile/profile.js', 'utf8')
  const wxml = fs.readFileSync('pages/profile/profile.wxml', 'utf8')

  assert.match(js, /saveProfile/)
  assert.match(js, /saveProfileDraft/)
  assert.match(js, /onChooseAvatar/)
  assert.match(js, /onNicknameInput/)
  assert.match(js, /onNicknameConfirm/)
  assert.match(wxml, /open-type="chooseAvatar"/)
  assert.match(wxml, /bindchooseavatar="onChooseAvatar"/)
  assert.match(wxml, /bindinput="onNicknameInput"/)
  assert.match(wxml, /bindconfirm="onNicknameConfirm"/)
  assert.match(wxml, /placeholder="点击填写微信昵称"/)
})

test('profile page replaces abilities with talent and gear template modules', () => {
  const js = fs.readFileSync('pages/profile/profile.js', 'utf8')
  const wxml = fs.readFileSync('pages/profile/profile.wxml', 'utf8')
  const css = fs.readFileSync('pages/profile/profile.wxss', 'utf8')

  assert.doesNotMatch(js, /abilities:\s*\[/)
  assert.doesNotMatch(wxml, /我的能力/)
  assert.match(js, /buildTemplateSummary/)
  assert.match(js, /deleteBuildTemplate/)
  assert.match(js, /hydrateTemplates\(\)/)
  assert.match(wxml, /天赋模板/)
  assert.match(wxml, /装备模板/)
  assert.match(wxml, /templateModules/)
  assert.match(wxml, /item\.count/)
  assert.match(wxml, /item\.recent/)
  assert.match(wxml, /template-meta-chip/)
  assert.match(wxml, /bindtap="deleteTemplate"/)
  assert.match(wxml, /data-id="\{\{template\.id\}\}"/)
  assert.match(css, /\.template-module/)
  assert.match(css, /\.template-delete-button/)
})
