const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')

test('simc page uses chat clarification before task submission', () => {
  const js = fs.readFileSync('pages/simulator/simc.js', 'utf8')
  const wxml = fs.readFileSync('pages/simulator/simc.wxml', 'utf8')
  const css = fs.readFileSync('pages/simulator/simc.wxss', 'utf8')

  assert.match(wxml, /chat-messages/)
  assert.match(wxml, /chat-context/)
  assert.doesNotMatch(wxml, /<view class="hero simulator-hero">/)
  assert.match(wxml, /wx:for="\{\{messages\}\}"/)
  assert.match(wxml, /chat-row-\{\{item\.role\}\}/)
  assert.match(wxml, /value="\{\{chatInput\}\}"/)
  assert.match(wxml, /bindinput="updateChatInput"/)
  assert.match(wxml, /bindtap="sendChatMessage"/)
  assert.match(wxml, /bindtap="submitConfirmedTask"/)
  assert.match(wxml, /disabled="\{\{!canSubmitTask \|\| submittingTask \|\| taskSubmitted\}\}"/)
  assert.match(wxml, /任务已提交/)
  assert.doesNotMatch(wxml, /最多\s*3\s*轮/)
  assert.match(js, /messages:\s*\[/)
  assert.doesNotMatch(js, /maxRounds:\s*3/)
  assert.doesNotMatch(js, /conversationRound\s*>=\s*this\.data\.maxRounds/)
  assert.doesNotMatch(js, /chatLocked/)
  assert.match(js, /sendChatMessage\(\)/)
  assert.match(js, /sendChatContent\(content\)/)
  assert.match(js, /submitConfirmedTask\(\)/)
  assert.match(js, /confirmOnly:\s*true/)
  assert.match(js, /saveTask:\s*true/)
  assert.match(js, /allowInsecureGuestRequest:\s*true/)
  assert.match(js, /canSubmitTask/)
  assert.match(js, /taskSubmitted/)
  assert.match(js, /auth:\s*true/)
  assert.doesNotMatch(js, /\/simc|角色名|服务器|角色数据/)
  assert.doesNotMatch(wxml, /\/simc|角色名|服务器|角色数据/)
  assert.match(js, /mode:\s*'simcraft_agent'/)
  assert.match(js, /runSimulation:\s*true/)
  assert.match(css, /\.chat-row-user/)
  assert.match(css, /\.chat-row-ai/)
  assert.match(css, /\.chat-composer/)
  assert.match(css, /\.send-button[\s\S]*width:\s*132rpx;/)
  assert.match(css, /\.task-submit-button\[disabled\]/)
  assert.match(css, /\.submit-button/)
  assert.match(css, /\.submit-ready/)
})

test('simc quick replies are sent immediately and clear stale suggestions', () => {
  const js = fs.readFileSync('pages/simulator/simc.js', 'utf8')

  assert.match(js, /useQuickReply\(event\)/)
  assert.match(js, /this\.sendChatContent\(reply\)/)
  assert.match(js, /quickReplies:\s*\[\]/)
  assert.doesNotMatch(js, /useQuickReply\(event\)[\s\S]{0,180}setData\(\{\s*chatInput:\s*reply\s*\}\)/)
})

test('simc page loads build context from specialization detail and confirms it', () => {
  const js = fs.readFileSync('pages/simulator/simc.js', 'utf8')
  const wxml = fs.readFileSync('pages/simulator/simc.wxml', 'utf8')

  assert.match(js, /SIMC_BUILD_CONTEXT_STORAGE_KEY/)
  assert.match(js, /onLoad\(options\)/)
  assert.match(js, /loadBuildContext\(options\)/)
  assert.match(js, /wx\.getStorageSync\(SIMC_BUILD_CONTEXT_STORAGE_KEY\)/)
  assert.match(js, /buildPromptFromContext\(context\)/)
  assert.match(js, /this\.sendChatContent\(prompt,\s*\{ buildContext: context \}\)/)
  assert.match(js, /pendingBuildContext/)
  assert.match(js, /buildContext:\s*this\.data\.pendingBuildContext/)
  assert.match(wxml, /context-source/)
  assert.match(wxml, /buildContextTitle/)
})

test('simc prompt includes front-end talent and gear simulator state', () => {
  const js = fs.readFileSync('pages/simulator/simc.js', 'utf8')

  assert.match(js, /context\.simulatorState \|\| \{\}/)
  assert.match(js, /talentState\.selectedNodes/)
  assert.match(js, /talentState\.simcHint/)
  assert.match(js, /gearState\.progressText/)
  assert.match(js, /gearState\.nextAction/)
})

test('simulator page renders simc agent clarification and summary cards', () => {
  const wxml = fs.readFileSync('pages/simulator/simc.wxml', 'utf8')
  const css = fs.readFileSync('pages/simulator/simc.wxss', 'utf8')
  const api = fs.readFileSync('pages/simulator/simulator-api.js', 'utf8')

  assert.match(wxml, /SimC 需求确认/)
  assert.match(wxml, /latestAnalysis\.agent\.quickReplies/)
  assert.doesNotMatch(wxml, /确认摘要/)
  assert.doesNotMatch(wxml, /生成的 SimC 模板/)
  assert.doesNotMatch(wxml, /latestAnalysis\.agent\.summaryCards/)
  assert.doesNotMatch(wxml, /latestAnalysis\.agent\.draftProfile/)
  assert.match(api, /agent:\s*\{/)
  assert.match(api, /needs_clarification/)
  assert.match(css, /\.quick-reply/)
  assert.doesNotMatch(css, /\.agent-summary-list/)
  assert.doesNotMatch(css, /\.agent-template/)
})

test('simulator page uses a dark code-console visual treatment', () => {
  const wxml = fs.readFileSync('pages/simulator/simc.wxml', 'utf8')
  const css = fs.readFileSync('pages/simulator/simc.wxss', 'utf8')

  assert.match(wxml, /background="#111111"/)
  assert.match(css, /\.chat-context[\s\S]*#493477/i)
  assert.match(css, /\.chat-input[\s\S]*background:\s*#101010;/)
  assert.match(css, /\.chat-input[\s\S]*color:\s*#e1e2e5;/)
  assert.match(css, /\.submit-button[\s\S]*background:\s*#8b3ff5;/)
})

test('smart analysis tab is a three-module entry hub without metrics', () => {
  const app = JSON.parse(fs.readFileSync('app.json', 'utf8'))
  const js = fs.readFileSync('pages/simulator/simulator.js', 'utf8')
  const wxml = fs.readFileSync('pages/simulator/simulator.wxml', 'utf8')
  const css = fs.readFileSync('pages/simulator/simulator.wxss', 'utf8')
  const api = fs.readFileSync('pages/simulator/simulator-api.js', 'utf8')

  assert.ok(app.pages.includes('pages/simulator/simc'))
  assert.ok(app.pages.includes('pages/simulator/wcl'))
  assert.ok(app.pages.includes('pages/simulator/task-detail'))
  assert.match(wxml, /<view class="hero simulator-hero">/)
  assert.doesNotMatch(wxml, /class="metrics"/)
  assert.doesNotMatch(wxml, /metric-card/)
  assert.match(wxml, /analysis-modules/)
  assert.match(wxml, /wx:for="\{\{analysisModules\}\}"/)
  assert.match(wxml, /任务列表/)
  assert.match(wxml, /data-task-id="\{\{item\.taskId\}\}"/)
  assert.match(wxml, /bindtap="openTaskDetail"/)
  assert.match(js, /openAnalysisModule\(event\)/)
  assert.match(js, /openTaskDetail\(event\)/)
  assert.match(js, /taskId:\s*task\.taskId/)
  assert.match(js, /wx\.navigateTo\(\{[\s\S]*\/pages\/simulator\/simc/)
  assert.match(js, /wx\.navigateTo\(\{[\s\S]*\/pages\/simulator\/wcl/)
  assert.match(js, /\/pages\/simulator\/task-detail\?id=/)
  assert.match(api, /navTitle:\s*'智能分析'/)
  assert.match(api, /analysisModules:\s*\[/)
  assert.match(api, /title:\s*'模拟 SimC'/)
  assert.match(api, /title:\s*'分析 WCL'/)
  assert.match(api, /title:\s*'任务列表'/)
  assert.match(css, /\.analysis-modules/)
  assert.match(css, /\.analysis-module-card/)
})

test('simulator task detail page renders saved task analysis', () => {
  const js = fs.readFileSync('pages/simulator/task-detail.js', 'utf8')
  const wxml = fs.readFileSync('pages/simulator/task-detail.wxml', 'utf8')
  const css = fs.readFileSync('pages/simulator/task-detail.wxss', 'utf8')
  const api = fs.readFileSync('pages/simulator/simulator-api.js', 'utf8')

  assert.match(js, /requestSimulatorTaskDetail/)
  assert.match(js, /loadTaskDetail\(options\.id/)
  assert.match(js, /normalizeTaskDetail\(task\)/)
  assert.match(wxml, /任务详情/)
  assert.match(wxml, /玩家问题/)
  assert.match(wxml, /AI 结论/)
  assert.match(wxml, /真实大秘境对标/)
  assert.match(wxml, /执行阶段/)
  assert.doesNotMatch(wxml, /生成的 SimC 模板/)
  assert.doesNotMatch(wxml, /SimC 执行摘要/)
  assert.match(wxml, /detail\.recommendations/)
  assert.match(wxml, /detail\.mythicPlusReference/)
  assert.match(wxml, /detail\.mythicPlusReferenceText/)
  assert.match(wxml, /detail\.buildContextText/)
  assert.match(wxml, /detail\.stages/)
  assert.doesNotMatch(wxml, /detail\.draftProfile/)
  assert.doesNotMatch(wxml, /detail\.simulationSummary/)
  assert.doesNotMatch(wxml, /detail\.llmContent/)
  assert.doesNotMatch(wxml, /AI 解读/)
  assert.match(wxml, /detail\.simcDps/)
  assert.match(wxml, /detail\.briefConclusion/)
  assert.match(api, /requestSimulatorTaskDetail\(taskId\)/)
  assert.match(css, /\.task-detail-hero/)
  assert.match(css, /\.build-context-box/)
  assert.doesNotMatch(css, /\.detail-code/)
})

test('wcl analysis page submits WCL questions through the simulator analyzer', () => {
  const app = JSON.parse(fs.readFileSync('app.json', 'utf8'))
  const js = fs.readFileSync('pages/simulator/wcl.js', 'utf8')
  const wxml = fs.readFileSync('pages/simulator/wcl.wxml', 'utf8')

  assert.ok(app.pages.includes('pages/simulator/wcl'))
  assert.match(js, /navTitle:\s*'分析 WCL'/)
  assert.match(wxml, /textarea[\s\S]*value="\{\{wclPrompt\}\}"/)
  assert.match(wxml, /bindtap="submitWclAnalysis"/)
  assert.match(js, /submitWclAnalysis\(\)/)
  assert.match(js, /mode:\s*'wcl'/)
  assert.match(js, /prompt:\s*this\.data\.wclPrompt/)
})
