const fs = require('node:fs')
const test = require('node:test')
const assert = require('node:assert/strict')

test('websim static page exposes the three planned modules and api hooks', () => {
  const html = fs.readFileSync('websim/index.html', 'utf8')
  const js = fs.readFileSync('websim/app.js', 'utf8')
  const css = fs.readFileSync('websim/app.css', 'utf8')

  assert.match(html, /天赋模拟器/)
  assert.match(html, /装备模拟器/)
  assert.match(html, /装备查询/)
  assert.match(html, /SimC 构筑工坊/)
  assert.match(html, /赛季校验中/)
  assert.match(html, /职业/)
  assert.match(html, /专精/)
  assert.match(html, /id="heroSelect"/)
  assert.match(html, /wowhead-selector-strip/)
  assert.match(html, /id="classSelectPreview"/)
  assert.match(html, /id="specSelectPreview"/)
  assert.match(html, /id="heroSelectPreview"/)
  assert.match(html, /id="scenarioSelectPreview"/)
  assert.match(html, /data-selector-button="class"/)
  assert.match(html, /id="classSelectorMenu"/)
  assert.match(html, /role="listbox"/)
  assert.match(html, /英雄天赋/)
  assert.match(html, /首领掉落/)
  assert.doesNotMatch(html, />Class</)
  assert.doesNotMatch(html, />Spec</)
  assert.match(js, /dataStatus/)
  assert.match(js, /WebSim 可交互结构/)
  assert.match(js, /\/api\/websim\/bootstrap/)
  assert.match(js, /\/api\/websim\/talents/)
  assert.match(js, /\/api\/websim\/gear/)
  assert.match(js, /\/api\/websim\/loot/)
  assert.match(js, /\/api\/websim\/profile/)
  assert.match(js, /\/api\/websim\/simulate/)
  assert.match(js, /talentState:\s*\{/)
  assert.match(js, /selectedNodes:\s*selectedTalentEntries\(\)/)
  assert.match(js, /talentEncodingErrorText/)
  assert.match(js, /hasSubmittableTalentSelection/)
  assert.match(js, /const hasTalentSelection = hasSubmittableTalentSelection\(payload\)/)
  assert.doesNotMatch(js, /if \(!payload\.talents \|\| readiness\.simcReadyCount < 1\)/)
  assert.match(js, /state\.slotGroups = payload\.slotGroups \|\| \[\]/)
  assert.match(js, /state\.baselineSet = payload\.baselineSet \|\| \[\]/)
  assert.match(js, /renderGearCandidates\(\)/)
  assert.match(js, /# candidate \$\{item\.slot\}=/)
  assert.match(js, /simcGearLines/)
  assert.match(js, /talentEncoding/)
  assert.match(js, /天赋编码未通过/)
  assert.match(css, /\.armory-layout/)
  assert.match(css, /\.journal-layout/)
  assert.match(css, /\.talent-tree/)
  assert.doesNotMatch(html, /id="loadPresetButton"/)
  assert.doesNotMatch(html, /id="importTalentsButton"/)
  assert.doesNotMatch(html, /id="exportTalentsButton"/)
  assert.match(html, /id="copyTalentsButton"/)
  assert.match(html, /id="resetTalentsButton"/)
  assert.doesNotMatch(html, /id="undoTalentsButton"/)
  assert.doesNotMatch(html, /id="redoTalentsButton"/)
  assert.match(html, /id="showTalentNamesButton"/)
  assert.match(html, /id="annotateTalentsButton"/)
  assert.match(html, /id="talentHelpButton"/)
  assert.match(html, /id="talentHelpPanel"/)
  assert.match(html, /id="talentPanelHeading"/)
  assert.match(html, /id="talentPanelEyebrow"/)
  assert.match(html, /天赋构筑工具/)
  assert.match(html, /显示名称/)
  assert.match(html, /标记模式/)
  assert.doesNotMatch(html, />Undo</)
  assert.doesNotMatch(html, />Redo</)
  assert.match(html, /复制链接/)
  assert.match(html, /帮助/)
  assert.doesNotMatch(html, /Talent Calculator/)
  assert.doesNotMatch(html, /Show Names/)
  assert.doesNotMatch(html, /Annotate/)
  assert.doesNotMatch(html, />Reset</)
  assert.doesNotMatch(html, />Link</)
  assert.doesNotMatch(html, />Help</)
  assert.match(html, /id="talentActionStatus"/)
  assert.match(html, /aria-live="polite"/)
  assert.match(html, /data-action-icon/)
  assert.match(html, /20260613-selector-focus-return/)
  assert.match(js, /talentPageTitle/)
  assert.match(js, /talentDocumentTitle/)
  assert.match(js, /syncTalentDocumentTitle/)
  assert.match(js, /talentPageEyebrow/)
  assert.match(js, /至暗之夜天赋模拟器/)
  assert.match(js, /document\.title = talentDocumentTitle\(\)/)
  assert.match(js, /heading\.textContent = talentPageTitle\(\)/)
  assert.match(js, /eyebrow\.textContent = talentPageEyebrow\(\)/)
  assert.match(js, /syncTalentDocumentTitle\(\)/)
  assert.match(js, /buildTalentExportCode/)
  assert.match(js, /talentSelectionFromLocation/)
  assert.match(js, /buildTalentRouteUrl/)
  assert.match(js, /buildTalentShareUrl/)
  assert.match(js, /syncTalentRoute/)
  assert.match(js, /syncLiveTalentRoute/)
  assert.match(js, /hasLiveTalentBuild/)
  assert.match(js, /includeBuild/)
  assert.match(js, /encodePvpBuildSelections/)
  assert.match(js, /decodePvpBuildSelections/)
  assert.match(js, /;pvp=\$\{encodePvpBuildSelections\(\)\}/)
  assert.match(js, /setPvpSelectionsForCurrentSpec\(pvpPayload/)
  assert.match(js, /talentHistoryPast/)
  assert.match(js, /talentHistoryFuture/)
  assert.match(js, /talentBuildSnapshot/)
  assert.match(js, /pushTalentHistorySnapshot/)
  assert.match(js, /restoreTalentBuildSnapshot/)
  assert.match(js, /undoTalentHistory/)
  assert.match(js, /redoTalentHistory/)
  assert.match(js, /isEditableShortcutTarget/)
  assert.match(js, /handleTalentHistoryShortcut/)
  assert.match(js, /event\.ctrlKey \|\| event\.metaKey/)
  assert.match(js, /if \(isEditableShortcutTarget\(event\.target\)\) return false/)
  assert.match(js, /tag === 'input' \|\| tag === 'textarea' \|\| tag === 'select'/)
  assert.match(js, /target\.isContentEditable/)
  assert.doesNotMatch(js, /undoTalentsButton/)
  assert.doesNotMatch(js, /redoTalentsButton/)
  assert.match(js, /setTalentHelpOpen\(false\)/)
  assert.match(js, /applyTalentRouteSelection/)
  assert.match(js, /history\.replaceState/)
  assert.match(js, /history\[method\]/)
  assert.match(js, /addEventListener\('popstate'/)
  assert.match(js, /searchParams\.delete\('build'\)/)
  assert.match(js, /searchParams\.delete\('talents'\)/)
  assert.match(js, /searchParams\.set\('build', buildTalentExportCode\(\)\)/)
  assert.match(js, /searchParams\.set\('class'/)
  assert.match(js, /params\.get\('build'\)/)
  assert.match(js, /talentFooterMarkup/)
  assert.match(js, /bindTalentFooterControls/)
  assert.match(js, /talentSearchTerm/)
  assert.match(js, /talentSearchFocusId/)
  assert.match(js, /talentSearchIndex/)
  assert.match(js, /搜索所有天赋/)
  assert.match(js, /talentSearchMatches/)
  assert.match(js, /normalizeTalentSearchIndex/)
  assert.match(js, /talentSearchControlsMarkup/)
  assert.match(js, /currentTalentSearchMatch/)
  assert.match(js, /setTalentSearchIndexToId/)
  assert.match(js, /revealTalentSearchMatch/)
  assert.match(js, /revealCurrentTalentSearchMatch/)
  assert.match(js, /focusTalentSearchNode/)
  assert.match(js, /focusTalentNodeById/)
  assert.match(js, /function focusTalentNodeById\(id, options = \{\}\)/)
  assert.match(js, /const reveal = Boolean\(options\.reveal\)/)
  assert.match(js, /if \(reveal && node\.scrollIntoView\)/)
  assert.match(js, /node\.focus\(\{ preventScroll: true \}\)/)
  assert.match(js, /focusTalentNodeById\(id, \{ reveal: true \}\)/)
  assert.match(js, /restoreTalentNodeFocus/)
  assert.match(js, /restoreChoiceOptionFocus/)
  assert.match(js, /requestAnimationFrame/)
  assert.match(js, /setTimeout\(\(\) => focusTalentNodeById\(id\), 80\)/)
  assert.match(js, /setTimeout\(\(\) => focusTalentNodeById\(id\), 320\)/)
  assert.match(js, /setTimeout\(\(\) => focusTalentNodeById\(id\), 760\)/)
  assert.match(js, /setTimeout\(\(\) => restoreTalentNodeFocus\(id\), 140\)/)
  assert.match(js, /focusTalentSearchInput/)
  assert.match(js, /jumpTalentSearchMatch/)
  assert.match(js, /revealCurrentTalentSearchMatch\(\)/)
  assert.doesNotMatch(js, /talentAbilitySearchMarkup/)
  assert.match(js, /clearTalentSearch/)
  assert.match(js, /searchInput\.addEventListener\('keydown'/)
  assert.match(js, /event\.key === 'Enter'/)
  assert.match(js, /event\.shiftKey \? -1 : 1/)
  assert.match(js, /key === 'Escape' && state\.talentSearchTerm/)
  assert.match(js, /event\.key === 'Escape' && state\.talentSearchTerm/)
  assert.doesNotMatch(js, /talentAbilitySearchInput/)
  assert.match(js, /text-field-input body-text/)
  assert.match(js, /footerMenuPanel/)
  assert.match(js, /footerImportDraft/)
  assert.match(js, /talentFooterPanelMarkup/)
  assert.match(js, /focusTalentFooterPanelInitial/)
  assert.match(js, /openTalentFooterPanel/)
  assert.match(js, /revealTalentFooterMenu/)
  assert.match(js, /talentFooterMenuItems/)
  assert.match(js, /focusTalentFooterMenuItem/)
  assert.match(js, /stepTalentFooterMenuFocus/)
  assert.match(js, /handleTalentFooterMenuButtonKeydown/)
  assert.match(js, /handleTalentFooterMenuKeydown/)
  assert.match(js, /menuButton\.addEventListener\('keydown', \(event\) => handleTalentFooterMenuButtonKeydown/)
  assert.match(js, /footerMenu\.addEventListener\('keydown', \(event\) => handleTalentFooterMenuKeydown/)
  assert.match(js, /event\.key === 'ArrowDown' \|\| event\.key === 'ArrowRight'/)
  assert.match(js, /closeTalentFooterMenu\(scope, true\)/)
  assert.match(js, /openTalentFooterPanel\(button\.dataset\.talentFooterPanel \|\| '', event\.detail === 0\)/)
  assert.match(js, /data-talent-footer-panel="import"/)
  assert.match(js, /data-talent-footer-panel="export"/)
  assert.match(js, /data-talent-footer-panel="share"/)
  assert.match(js, /data-talent-footer-panel="character"/)
  assert.match(js, /talentFooterImportInput/)
  assert.match(js, /data-talent-footer-action="import-panel"/)
  assert.match(js, /copy-panel/)
  assert.match(js, /copy-export/)
  assert.match(js, /aria-label="关闭">×<\/button>/)
  assert.match(js, /aria-label="清空搜索">×<\/button>/)
  assert.match(js, /分享构筑/)
  assert.match(js, /导出当前构筑/)
  assert.match(js, /复制分享链接/)
  assert.match(js, /复制导出字符串/)
  assert.match(js, /导入构筑/)
  assert.match(js, /粘贴 WebSim 构筑字符串/)
  assert.match(js, /载入角色/)
  assert.match(js, /服务器/)
  assert.match(js, /角色名/)
  assert.match(js, /PvP 天赋：/)
  assert.match(js, /aria-label="PvP 天赋"/)
  assert.doesNotMatch(js, /脳/)
  assert.match(js, /data-talent-search-clear/)
  assert.match(js, /data-talent-search-step/)
  assert.match(js, /talent-footer-pvp-slot/)
  assert.match(js, /pvpTalentOptions/)
  assert.match(js, /pvpSlotIndexFromButton/)
  assert.match(js, /pvpSlotButtons/)
  assert.match(js, /focusPvpSlotByDirection/)
  assert.match(js, /handlePvpSlotKeydown/)
  assert.match(js, /talentPvpPicker/)
  assert.match(js, /showPvpTalentPicker/)
  assert.match(js, /pvpPickerOptions/)
  assert.match(js, /focusPvpPickerOption/)
  assert.match(js, /focusPvpPickerInitial/)
  assert.match(js, /focusPvpSlot/)
  assert.match(js, /hidePvpTalentPickerFromKeyboard/)
  assert.match(js, /handlePvpPickerKeydown/)
  assert.match(js, /picker\.addEventListener\('keydown', handlePvpPickerKeydown\)/)
  assert.match(js, /selectPvpTalent\(state\.activePvpSlot, option\.dataset\.pvpOption \|\| '', true\)/)
  assert.match(js, /clearPvpTalent\(state\.activePvpSlot, true\) \|\| hidePvpTalentPickerFromKeyboard\(\)/)
  assert.match(js, /showPvpTalentPicker\(slotIndex, button, event\)/)
  assert.match(js, /button\.addEventListener\('keydown', \(event\) => handlePvpSlotKeydown\(event, button\)\)/)
  assert.match(js, /key === 'ArrowRight' \|\| key === 'ArrowDown'/)
  assert.match(js, /if \(!clearPvpTalent\(slotIndex\)\) hidePvpTalentPicker\(\)/)
  assert.match(js, /selectPvpTalent/)
  assert.match(js, /clearPvpTalent/)
  assert.match(js, /pvpTalents/)
  assert.match(js, /search-match/)
  assert.match(js, /search-current/)
  assert.match(js, /search-dimmed/)
  assert.match(js, /flashTalentAction/)
  assert.match(js, /action-flash/)
  assert.match(js, /talent-action-button\.action-flash/)
  assert.match(js, /parentsSatisfied/)
  assert.match(js, /pointRequirementSatisfied/)
  assert.match(js, /pointRequirementFor/)
  assert.match(js, /missingParentNodesFor/)
  assert.match(js, /talentDisabledReason/)
  assert.match(js, /setBlockedTalentFeedback/)
  assert.match(js, /talentUnlockStepsFor/)
  assert.match(js, /talentUnlockActionPriority/)
  assert.match(js, /talentUnlockPrimaryStep/)
  assert.match(js, /talentUnlockProgressFor/)
  assert.match(js, /talentUnlockProgressMarkup/)
  assert.match(js, /talentUnlockGuideMarkup/)
  assert.match(js, /actionLabel/)
  assert.match(js, /推荐加点/)
  assert.match(js, /step\.state = 'gate'/)
  assert.match(js, /talentTooltipUnlockGuideHtml/)
  assert.match(js, /talentBlockedFlashMessage/)
  assert.match(js, /clearBlockedTalentFeedback/)
  assert.match(js, /restoreFocus/)
  assert.match(js, /restoreTalentNodeFocus\(blockedId\)/)
  assert.match(js, /scheduleBlockedTalentFeedbackClear/)
  assert.match(js, /clearResolvedBlockedTalentFeedback/)
  assert.match(js, /canIncreaseTalent\(blockedNode\) \|\| rankFor\(blockedNode\) >= maxRankFor\(blockedNode\)/)
  assert.match(js, /const clearedBlockedFeedback = clearResolvedBlockedTalentFeedback\(\)/)
  assert.match(js, /if \(!clearedBlockedFeedback && state\.blockedTalentId\) scheduleBlockedTalentFeedbackClear\(\)/)
  assert.match(js, /restoreTalentNodeFocus\(id\)/)
  assert.match(js, /markTalentUnlockStepFocus/)
  assert.match(js, /setTalentUnlockStepPreview/)
  assert.match(js, /bindTalentUnlockStepPreview/)
  assert.match(js, /focusTalentUnlockStep/)
  assert.match(js, /applyTalentUnlockStepRank/)
  assert.match(js, /data-unlock-guide/)
  assert.match(js, /data-unlock-step/)
  assert.match(js, /data-unlock-step-add/)
  assert.match(js, /data-unlock-step-continue/)
  assert.match(js, /data-unlock-dismiss/)
  assert.match(js, /clearBlockedTalentFeedback\(\{ restoreFocus: true \}\)/)
  assert.match(js, /data-unlock-progress/)
  assert.match(js, /data-progress-tone/)
  assert.match(js, /data-target-id/)
  assert.match(js, /websim_talent_unlock_step_focus/)
  assert.match(js, /websim_talent_unlock_step_add/)
  assert.match(js, /blockedTalentId/)
  assert.match(js, /websim_talent_blocked/)
  assert.match(js, /pointCapFor/)
  assert.match(js, /pointCapReached/)
  assert.match(js, /orderedTreeSections/)
  assert.match(js, /treeReqLevelFor/)
  assert.match(js, /gateRequirementsForNodes/)
  assert.match(js, /treeGateStatus/)
  assert.match(js, /treeHeaderMarkup/)
  assert.match(js, /下一道门槛/)
  assert.match(js, /全部门槛已开启/)
  assert.match(js, /starterTalentRanks/)
  assert.match(js, /loadStarterTalentRanks/)
  assert.match(js, /state\.baseTalentRanks = \{\}/)
  assert.doesNotMatch(js, /state\.baseTalentRanks = \{ \.\.\.state\.starterTalentRanks \}/)
  assert.match(js, /grantedRankFor/)
  assert.match(js, /isGrantedTalent/)
  assert.match(js, /grantedChoicePeerFor/)
  assert.match(js, /fixedTalentMessage/)
  assert.match(js, /state\.baseTalentRanks\[node\.id\] = grantedRank/)
  assert.match(js, /state\.talentRanks = \{ \.\.\.state\.baseTalentRanks, \.\.\.state\.starterTalentRanks \}/)
  assert.match(js, /state\.starterTalentRanks\[node\.id\]/)
  assert.match(js, /需求等级/)
  assert.match(js, /已投入/)
  assert.match(js, /pointCap: 34/)
  assert.match(js, /pointCap: 13/)
  assert.match(js, /sectionData/)
  assert.match(js, /talent-calculator-frame/)
  assert.match(js, /talentZoom/)
  assert.match(js, /talentZoomSteps/)
  assert.match(js, /normalizeTalentZoom/)
  assert.match(js, /talentZoomPercent/)
  assert.match(js, /applyTalentZoomToDom/)
  assert.match(js, /setTalentZoom/)
  assert.match(js, /shiftTalentZoom/)
  assert.match(js, /talentViewControlsMarkup/)
  assert.match(js, /bindTalentViewControls/)
  assert.match(js, /data-talent-zoom="out"/)
  assert.match(js, /data-talent-zoom="reset"/)
  assert.match(js, /data-talent-zoom="in"/)
  assert.match(js, /tree-header-progress/)
  assert.match(js, /role="meter"/)
  assert.match(js, /tree-header-progress-fill/)
  assert.match(js, /tree-header-next-gate/)
  assert.match(js, /tree-header-attention/)
  assert.match(js, /data-next-gate-state/)
  assert.match(js, /data-gate-state/)
  assert.match(js, /已开启/)
  assert.match(js, /talent-tree-headers/)
  assert.match(js, /canIncreaseTalent/)
  assert.match(js, /clearInvalidTalentRanks/)
  assert.match(js, /recentTalentId/)
  assert.match(js, /recentTalentTone/)
  assert.match(js, /markRecentTalent/)
  assert.match(js, /active\.dataset\.talentId === id/)
  assert.match(js, /if \(restoreFocus\) restoreTalentNodeFocus\(id\)/)
  assert.match(js, /talentRankChangeMessage/)
  assert.match(js, /applyTalentRankDelta/)
  assert.match(js, /已加入 1 点/)
  assert.match(js, /已移除 1 点/)
  assert.match(js, /没有可移除的点数/)
  assert.match(js, /childNodesFor/)
  assert.match(js, /relatedTalentIdsFor/)
  assert.match(js, /talentPathContextFor/)
  assert.match(js, /talentLinkEndpoints/)
  assert.match(js, /talentNodeButtonMeta/)
  assert.match(js, /orderedTalentNodeButtons/)
  assert.match(js, /nearestTalentNodeButton/)
  assert.match(js, /focusTalentNodeByDirection/)
  assert.match(js, /decrementTalentNodeRank/)
  assert.match(js, /handleTalentNodeKeydown/)
  assert.match(js, /const activatesNode = key === 'Enter' \|\| key === ' '/)
  assert.match(js, /button && button\.click/)
  assert.match(js, /const changed = applyTalentRankDelta\(node, event\.shiftKey \? -1 : 1, \{ restoreFocus: true \}\)/)
  assert.match(js, /selected: next > 0,\s+changed/)
  assert.match(js, /websim_talent_granted_blocked/)
  assert.match(js, /restoreTalentNodeFocus\(id\)/)
  assert.match(js, /if \(state\.annotateMode\)/)
  assert.match(js, /没有可移除的标记/)
  assert.match(js, /decrementTalentNodeRank\(node, true\)/)
  assert.match(js, /data-tree-key/)
  assert.match(js, /data-row/)
  assert.match(js, /data-col/)
  assert.match(js, /setTalentHoverState/)
  assert.match(js, /const hoveredId = active && node \? node\.id : ''/)
  assert.match(js, /classList\.toggle\('hovered', Boolean\(hoveredId && id === hoveredId\)\)/)
  assert.match(js, /classList\.remove\('ancestor-related', 'choice-related', 'descendant-related', 'related', 'dimmed'\)/)
  assert.match(js, /classList\.remove\('hover-path', 'upstream-path', 'downstream-path', 'dimmed'\)/)
  assert.doesNotMatch(js, /classList\.toggle\('dimmed', active && !isRelated\)/)
  assert.doesNotMatch(js, /classList\.toggle\('hover-path'/)
  assert.doesNotMatch(js, /classList\.toggle\('upstream-path'/)
  assert.doesNotMatch(js, /classList\.toggle\('downstream-path'/)
  assert.match(js, /blockedUnlockIds/)
  assert.match(js, /blockedUnlockLinks/)
  assert.match(js, /unlock-route/)
  assert.match(js, /unlock-route-ready/)
  assert.match(js, /unlock-route-missing/)
  assert.match(js, /unlock-path/)
  assert.match(js, /choiceGroup/)
  assert.match(js, /activeChoiceNodeId/)
  assert.match(js, /choiceGroupLabel/)
  assert.match(js, /choiceNodeSpread/)
  assert.match(js, /choiceNodeBadgeMarkup/)
  assert.match(js, /talentChoiceGroupMarkup/)
  assert.match(js, /visualTalentNodeFor/)
  assert.match(js, /visualTalentNodes/)
  assert.match(js, /visualNodes\.map/)
  assert.match(js, /const treeMinHeight/)
  assert.match(js, /--tree-min-height/)
  assert.match(js, /function talentChoiceGroupMarkup\(nodes, metrics\) {\s+return ''/)
  assert.match(js, /const choiceGroup = choice && node\.choiceGroup \? choiceGroupNodes\(node\) : \[\]/)
  assert.match(js, /const interactiveChoice = Boolean\(node\.choiceGroup && choiceGroup\.length > 1\)/)
  assert.match(js, /--choice-offset-x:\$\{choiceSpread\.x\}px/)
  assert.match(js, /choice-split/)
  assert.match(js, /\$\{group\.length\}选1/)
  assert.match(js, /const ariaDisabled = granted \|\| \(interactiveChoice \? false : \(locked \|\| capped\)\)/)
  assert.match(js, /data-granted-rank/)
  assert.match(js, /granted \? 'granted fixed' : ''/)
  assert.match(js, /默认赠送，不能修改/)
  assert.match(js, /talentGateCandidateNodesFor/)
  assert.match(js, /talentBlockingContextFor/)
  assert.match(js, /blockedUnlockContext/)
  assert.match(js, /talentTreeImage/)
  assert.match(js, /talentGateMarkup/)
  assert.match(js, /selectedChoicePeerFor/)
  assert.match(js, /activeChoiceNode/)
  assert.match(js, /previewChoiceOption/)
  assert.match(js, /restoreChoicePickerHover/)
  assert.match(js, /choicePickerOptions/)
  assert.match(js, /choiceDisabledState/)
  assert.match(js, /focusChoicePickerOption/)
  assert.match(js, /focusChoicePickerInitial/)
  assert.match(js, /hideChoicePickerFromKeyboard/)
  assert.match(js, /handleChoicePickerKeydown/)
  assert.match(js, /picker\.addEventListener\('keydown', handleChoicePickerKeydown\)/)
  assert.match(js, /event\.key === 'ArrowDown' \|\| event\.key === 'ArrowRight'/)
  assert.match(js, /event\.key === 'ArrowUp' \|\| event\.key === 'ArrowLeft'/)
  assert.match(js, /event\.key === 'Home'/)
  assert.match(js, /event\.key === 'End'/)
  assert.match(js, /const choiceId = option\.dataset\.choiceOption \|\| ''/)
  assert.match(js, /chooseChoiceOption\(choiceId, true\)/)
  assert.match(js, /restoreChoiceOptionFocus\(choiceId\)/)
  assert.match(js, /if \(restoreFocus\) restoreTalentNodeFocus\(id\)/)
  assert.match(js, /key === 'Backspace' \|\| key === 'Delete'/)
  assert.match(js, /button\.addEventListener\('keydown', \(event\) => handleTalentNodeKeydown/)
  assert.match(js, /pointerenter', \(\) => previewChoiceOption/)
  assert.match(js, /pointerleave', restoreChoicePickerHover/)
  assert.match(js, /talentChoicePicker/)
  assert.match(js, /isChoicePickerVisible/)
  assert.match(js, /showChoicePicker/)
  assert.match(js, /state\.activeChoiceNodeId !== node\.id/)
  assert.match(js, /state\.activeChoiceNodeId === node\.id && isChoicePickerVisible\(\)/)
  assert.match(js, /setTalentHoverState\(node, true\)/)
  assert.match(js, /choicePickerOptionHtml/)
  assert.match(js, /choicePickerHeaderHtml/)
  assert.match(js, /choiceBlockedTalentFeedback/)
  assert.match(js, /websim_talent_choice_blocked/)
  assert.match(js, /选择一个天赋/)
  assert.match(js, /role="menuitem"/)
  assert.match(js, /websim_talent_choice_open/)
  assert.match(js, /websim_talent_choice_select/)
  assert.match(js, /choice-selected/)
  assert.match(js, /choice-alternate/)
  assert.match(js, /data-choice-state/)
  assert.match(js, /data-choice-option-state/)
  assert.match(js, /data-link-state/)
  assert.match(js, /data-link-shape="edge"/)
  assert.match(js, /<path class="talent-link/)
  assert.match(js, /gate-locked/)
  assert.match(js, /blocked-path/)
  assert.match(js, /required-missing/)
  assert.match(js, /talent-hit-target/)
  assert.match(js, /点数上限已满/)
  assert.match(js, /talent-calculator-chrome/)
  assert.match(js, /talentTooltipHtml/)
  assert.match(js, /talentRankEntries/)
  assert.match(js, /talentHasRankDetails/)
  assert.match(js, /talentTooltipTitleText/)
  assert.match(js, /talentRankDetailHtml/)
  assert.match(js, /tooltip-rank-details/)
  assert.match(js, /tooltip-rank-detail/)
  assert.match(js, /Rank \$\{escapeHtml\(entry\.rank\)\}/)
  assert.match(js, /updateTalentTooltip/)
  assert.match(js, /hideTalentTooltipOutsideNode/)
  assert.match(js, /getBoundingClientRect/)
  assert.match(js, /flipX/)
  assert.match(js, /flipY/)
  assert.match(js, /Math\.max\(260, pickerRect\.width/)
  assert.match(js, /Math\.max\(220, rect\.width/)
  assert.match(js, /selectorPreviewHtml/)
  assert.match(js, /selectorOptionsFor/)
  assert.match(js, /subtitle: '职业'/)
  assert.match(js, /subtitle: '专精'/)
  assert.match(js, /classMeta\.label \|\| state\.classKey, '职业'/)
  assert.match(js, /specMeta\.label \|\| state\.specKey, '专精'/)
  assert.doesNotMatch(js, /subtitle: item\.labelEn/)
  assert.match(js, /currentSpecMeta\(\)\.heroTrees/)
  assert.match(js, /renderSelectorMenu/)
  assert.match(js, /toggleSelectorMenu/)
  assert.match(js, /selectSelectorOption/)
  assert.match(js, /focusSelectorPreview/)
  assert.match(js, /focusSelectorPreview\(kind\)/)
  assert.match(js, /data-search/)
  assert.match(js, /option\.dataset\.search/)
  assert.match(js, /split\(\/\\s\+\/\)/)
  assert.match(js, /focusSelectorEdge/)
  assert.match(js, /focusSelectorMatch/)
  assert.match(js, /event\.key === 'Home'/)
  assert.match(js, /event\.key === 'End'/)
  assert.match(js, /event\.key\.length === 1/)
  assert.match(js, /setSelectorPreview/)
  assert.match(js, /scenarioSubtitle/)
  assert.match(js, /choiceGroupNodes/)
  assert.match(js, /talentChromeIconStripMarkup/)
  assert.match(js, /talentChromeIconButton/)
  assert.match(js, /talentChromeTabButtons/)
  assert.match(js, /focusTalentChromeTab/)
  assert.match(js, /selectTalentChromeTab/)
  assert.match(js, /handleTalentChromeTabKeydown/)
  assert.match(js, /button\.addEventListener\('keydown', \(event\) => handleTalentChromeTabKeydown/)
  assert.match(js, /key === 'ArrowRight' \|\| key === 'ArrowDown'/)
  assert.match(js, /key === 'ArrowLeft' \|\| key === 'ArrowUp'/)
  assert.match(js, /heroTreeIconUrl/)
  assert.match(js, /heroFeatureMarkup/)
  assert.match(js, /data-talent-nav-kind/)
  assert.match(js, /showTalentNames/)
  assert.match(js, /annotateMode/)
  assert.match(js, /talentAnnotations/)
  assert.match(js, /toggleTalentAnnotation/)
  assert.match(js, /clearTalentAnnotations/)
  assert.match(js, /updateTalentToolbarState/)
  assert.match(js, /websim_talent_annotate/)
  assert.match(js, /pointerenter/)
  assert.match(js, /mouseover/)
  assert.match(js, /showTooltipFromFocus/)
  assert.match(js, /tooltip-topline/)
  assert.match(js, /tooltip-icon/)
  assert.match(js, /需要 \$\{escapeHtml\(requires\)\}/)
  ;[
    /Search All Talents/,
    /Next Gate/,
    /All Gates Open/,
    /Req Level/,
    /Point added/,
    /Point removed/,
    /No points to remove/,
    /No marker to remove/,
    /Choose one talent/,
    /point cap reached/,
    /Requires \$\{escapeHtml\(requires\)\}/,
    /Share Build/,
    /Export Current Build/,
    /Import Build/,
    /Load Character/,
    /PvP Talents/,
    /Clear Slot/,
    /Talent build tools/,
    /Link copied/,
    /Help open/,
    /Help closed/,
    /Action failed/
  ].forEach((pattern) => assert.doesNotMatch(js, pattern))
  assert.match(js, /data-talent-id/)
  assert.match(js, /websim:\$\{state\.classKey\}:\$\{state\.specKey\}:\$\{state\.heroKey/)
  assert.match(js, /websim_hero_change/)
  assert.match(js, /contextmenu/)
  assert.match(css, /\.wowhead-talent-board/)
  assert.match(css, /\.talent-calculator-frame/)
  assert.match(css, /--talent-board-min-width: 1280px/)
  assert.match(css, /--talent-board-columns/)
  assert.match(css, /min-width: var\(--talent-board-min-width/)
  assert.match(css, /--talent-zoom/)
  assert.match(css, /--talent-node-size/)
  assert.match(css, /--talent-icon-size/)
  assert.match(css, /--talent-row-size/)
  assert.match(css, /\.talent-view-controls/)
  assert.match(css, /\.talent-view-button/)
  assert.match(css, /\.talent-view-label/)
  assert.match(css, /\.talent-tree-headers/)
  assert.match(css, /\.talent-calculator-chrome/)
  assert.match(css, /\.talent-footer/)
  assert.match(css, /\.talent-footer-inner/)
  assert.match(css, /\.talent-footer-select/)
  assert.match(css, /\.talent-footer-menu/)
  assert.match(css, /\.talent-footer-panel/)
  assert.match(css, /\.talent-footer-panel-code/)
  assert.match(css, /\.talent-footer-panel-primary/)
  assert.match(css, /\.talent-footer-character-fields/)
  assert.match(css, /\.talent-footer-search-input/)
  assert.match(css, /\.talent-footer-search-input\.open/)
  assert.doesNotMatch(css, /\.talent-abilities-search/)
  assert.match(css, /\.talent-search-nav/)
  assert.match(css, /\.talent-search-nav\.active/)
  assert.match(css, /\.talent-search-step/)
  assert.match(css, /\.talent-search-count/)
  assert.match(js, /text-field-input body-text/)
  assert.match(css, /\.talent-footer-pvp-slot/)
  assert.match(css, /\.talent-footer-pvp-cover/)
  assert.match(css, /\.talent-footer-frill/)
  assert.match(css, /\.talent-pvp-picker/)
  assert.match(css, /\.talent-pvp-picker\.visible/)
  assert.match(css, /\.talent-pvp-option/)
  assert.match(css, /\.talent-pvp-option\.selected/)
  assert.match(css, /\.talent-pvp-option\.disabled/)
  assert.match(css, /\.talent-pvp-clear/)
  assert.match(css, /bg-stone-texture-long2\.webp/)
  assert.match(css, /talents-node-pvp-green\.png/)
  assert.match(css, /\.talent-icon-strip/)
  assert.match(css, /\.talent-icon-strip-frame/)
  assert.match(css, /\.talent-chrome-tab/)
  assert.match(css, /\.talent-chrome-tab\.active/)
  assert.match(css, /\.talent-icon-divider/)
  assert.match(css, /\.talent-build-summary/)
  assert.match(css, /\.talent-hero-feature/)
  assert.match(css, /\.talent-hero-emblem/)
  assert.match(css, /\.talent-column-hero \.talent-grid-inner/)
  assert.match(css, /\.tree-header-title/)
  assert.match(css, /\.tree-header-stats/)
  assert.match(css, /\.tree-header-next-gate/)
  assert.match(css, /\.tree-header-progress/)
  assert.match(css, /\.tree-header-progress-fill/)
  assert.match(css, /\.tree-header-progress-complete/)
  assert.match(css, /\.tree-header-attention/)
  assert.match(css, /\.talent-gate\.satisfied/)
  assert.match(css, /\.talent-gate\.locked/)
  assert.match(css, /width: min\(1760px, calc\(100vw - 28px\)\)/)
  assert.doesNotMatch(css, /min-width: 1320px/)
  assert.doesNotMatch(css, /minmax\(500px, 1\.18fr\) minmax\(330px, 0\.78fr\) minmax\(500px, 1\.18fr\)/)
  assert.match(css, /\.talent-action-button/)
  assert.match(css, /\.talent-action-status/)
  assert.match(css, /\.talent-unlock-guide/)
  assert.match(css, /\.talent-unlock-guide-action/)
  assert.match(css, /\.talent-unlock-guide-dismiss/)
  assert.match(css, /\.talent-unlock-progress/)
  assert.match(css, /\.talent-unlock-progress-item/)
  assert.match(css, /\.talent-unlock-steps/)
  assert.match(css, /\.talent-unlock-steps-item/)
  assert.match(css, /\.talent-unlock-steps-button/)
  assert.match(css, /\.talent-unlock-step-add/)
  assert.match(css, /\.talent-help-popover/)
  assert.match(css, /@keyframes talent-action-flash/)
  assert.match(css, /\.wowhead-selector-strip/)
  assert.match(css, /\.selector-card-button/)
  assert.match(css, /\.selector-menu/)
  assert.match(css, /\.selector-option/)
  assert.match(css, /\.selector-option\.selected/)
  assert.match(css, /\.selector-card-value/)
  assert.match(css, /\.selector-card-icon/)
  assert.match(css, /\.selector-card \.native-selector/)
  assert.match(css, /--tree-image/)
  assert.match(css, /--tree-min-height/)
  assert.match(css, /\.talent-node\.shape-apex/)
  assert.match(css, /\.talent-node\.shape-apex \.talent-icon-frame/)
  assert.match(css, /\.talent-gates/)
  assert.match(css, /\.talent-choice-groups/)
  assert.match(css, /\.talent-choice-group/)
  assert.match(css, /\.talent-choice-badge/)
  assert.match(css, /\.talent-node\.choice-split/)
  assert.match(css, /translate: var\(--choice-offset-x/)
  assert.match(css, /\.talent-gate/)
  assert.match(css, /\.talent-gate::after/)
  assert.match(css, /\.talent-link\.active/)
  assert.match(css, /\.talent-link\.available/)
  assert.match(css, /\.talent-link\.locked/)
  assert.match(css, /\.talent-link\.gate-locked/)
  assert.match(css, /\.talent-link\.blocked-path/)
  assert.match(css, /\.talent-link\.required-missing/)
  assert.match(css, /\.talent-link\.unlock-path/)
  assert.match(css, /\.talent-link\[data-link-shape="edge"\]/)
  assert.match(css, /--talent-layer-top: 16px/)
  assert.match(css, /--talent-layer-left: 14px/)
  assert.match(css, /width: calc\(100% - var\(--talent-layer-left\) - var\(--talent-layer-right\)\)/)
  assert.match(css, /height: calc\(100% - var\(--talent-layer-top\) - var\(--talent-layer-bottom\)\)/)
  assert.match(css, /\.talent-link\.recent/)
  assert.match(css, /stroke-linecap: round/)
  assert.match(css, /stroke-linejoin: round/)
  assert.match(css, /shape-rendering: geometricPrecision/)
  assert.match(css, /@keyframes talent-link-pulse/)
  assert.match(css, /\.talent-node\.choice/)
  assert.match(css, /\.talent-choice-picker/)
  assert.match(css, /\.talent-choice-picker-header/)
  assert.match(css, /\.talent-choice-picker-options/)
  assert.match(css, /\.talent-choice-option/)
  assert.match(css, /\.talent-choice-option\.selected/)
  assert.match(css, /\.talent-choice-option\.granted/)
  assert.match(css, /\.talent-choice-option\.disabled/)
  assert.match(css, /\.talent-choice-option\.gate-locked/)
  assert.match(css, /\.talent-choice-option\.missing-parent/)
  assert.match(css, /\.talent-choice-option\.capped/)
  assert.match(css, /\.talent-node\.choice-open/)
  assert.match(css, /\.talent-node\.choice-open::after/)
  assert.match(css, /\.talent-node\.choice-selected/)
  assert.match(css, /\.talent-node\.choice-alternate/)
  assert.match(css, /\.talent-node\.search-match/)
  assert.match(css, /\.talent-node\.search-current/)
  assert.match(css, /\.talent-node\.search-dimmed/)
  assert.match(css, /\.talent-node\.search-dimmed:not\(\.search-match\):focus/)
  assert.match(css, /\.talent-node\.search-dimmed:not\(\.search-match\):focus-visible/)
  assert.match(css, /position: absolute;\s+top: auto;[\s\S]+bottom: calc\(\(var\(--talent-node-size\) - var\(--talent-icon-size\)\) \/ 2 - 5px\)/)
  assert.match(css, /\.wowhead-talent-board \.talent-node\.selected,\s+\.wowhead-talent-board \.talent-node\.choice-selected {\s+border-color: transparent;\s+background: transparent;/)
  assert.match(css, /border-color: #b88a3c/)
  assert.match(css, /border-color: #d7b36a/)
  assert.match(css, /\.talent-node\.granted/)
  assert.match(css, /\.talent-node\.granted \.talent-icon-frame/)
  assert.match(css, /\.talent-node\.granted \.talent-rank/)
  assert.match(css, /\.talent-node\.available/)
  assert.match(css, /\.talent-node\.maxed/)
  assert.match(css, /\.talent-node\.capped/)
  assert.match(css, /\.talent-hit-target/)
  assert.match(css, /\.talent-node\.blocked-attempt/)
  assert.match(css, /\.talent-node\.required-missing/)
  assert.match(css, /\.talent-node\.unlock-route/)
  assert.match(css, /\.talent-node\.unlock-route-ready/)
  assert.match(css, /\.talent-node\.unlock-step-preview/)
  assert.match(css, /\.talent-node\.unlock-step-focus/)
  assert.match(css, /\.talent-gate\.attention/)
  assert.match(css, /@keyframes talent-blocked-nudge/)
  assert.match(css, /\.talent-node\.annotated/)
  assert.match(css, /Wowhead-style talent icon skin/)
  assert.match(css, /-webkit-text-stroke/)
  assert.match(css, /#25d84c/)
  assert.match(css, /grayscale\(1\) brightness\(0\.38\)/)
  assert.match(css, /\.talent-annotation/)
  assert.match(css, /\.talent-tree\.show-names/)
  assert.match(css, /\.talent-tree\.annotate-mode/)
  assert.match(css, /\.talent-node\.recent/)
  assert.match(css, /\.talent-node\.recent-remove::before/)
  assert.match(css, /\.talent-node\.recent-remove \.talent-icon-frame/)
  assert.match(css, /\.talent-node::after/)
  assert.match(css, /minmax\(var\(--talent-row-size\), 1fr\)/)
  assert.match(css, /minmax\(var\(--talent-row-size-names\), 1fr\)/)
  assert.match(css, /@keyframes talent-node-pulse/)
  assert.match(css, /\.talent-node:not\(\.locked\):hover/)
  assert.match(css, /repeat\(var\(--talent-rows\), minmax\(62px, 1fr\)\)/)
  assert.match(css, /\.tooltip-title/)
  assert.match(css, /\.tooltip-topline/)
  assert.match(css, /\.tooltip-icon/)
  assert.match(css, /\.tooltip-note\.warning/)
  assert.match(css, /\.tooltip-note\.cap/)
  assert.match(css, /\.tooltip-note\.granted/)
  assert.match(css, /\.talent-tooltip\.granted \.tooltip-status-line/)
  assert.match(css, /\.tooltip-rank-details/)
  assert.match(css, /\.tooltip-rank-detail/)
  assert.match(css, /\.tooltip-rank-detail strong/)
  assert.match(css, /\.tooltip-rank-detail p/)
  assert.match(css, /\.tooltip-unlock-guide/)
  assert.match(css, /\.tooltip-unlock-steps/)
  assert.match(css, /\.tooltip-unlock-steps-item/)
  assert.match(css, /\.tooltip-unlock-progress/)
  assert.match(css, /\.tooltip-unlock-progress-item/)
  assert.match(css, /\.talent-tooltip\.capped/)
  assert.match(css, /2147483647/)
  assert.match(css, /width: 320px/)
  assert.match(css, /width: min\(374px, calc\(100vw - 20px\)\)/)
  assert.match(css, /width: var\(--talent-node-size\)/)
  assert.match(css, /top: auto/)
  assert.match(css, /bottom: calc\(\(var\(--talent-node-size\) - var\(--talent-icon-size\)\) \/ 2 - 5px\)/)
  assert.match(css, /#ffd100/)
  assert.match(css, /right: -53px/)
  assert.match(css, /\.talent-tooltip/)
})

test('websim frontend helpers normalize gear and filter dungeon loot', () => {
  const helpers = require('../websim/app')
  const normalized = helpers.normalizeGearItem({
    itemId: 249343,
    slot: 'trinket1',
    name: 'Gaze of the Alnseer',
    enchantId: 123
  })

  assert.equal(normalized.itemId, '249343')
  assert.equal(normalized.slot, 'trinket1')
  assert.equal(normalized.name, 'Gaze of the Alnseer')
  assert.equal(normalized.simcReady, false)

  const normalizedLootRow = helpers.normalizeGearItem({
    id: 'boss-1:249343',
    itemId: 249343,
    slot: 'trinket1',
    name: 'Gaze of the Alnseer',
    sourceType: 'verifiedLoot'
  })
  assert.equal(normalizedLootRow.itemId, '249343')
  assert.equal(normalizedLootRow.simcReady, false)
  assert.ok(normalizedLootRow.missingFields.includes('ilevel'))

  const normalizedPresetRow = helpers.normalizeGearItem({
    itemId: 250111,
    slot: 'wrists',
    name: 'Preset Bracers',
    sourceType: 'simcPreset'
  })
  assert.equal(helpers.canonicalGearSlot('wrists'), 'wrist')
  assert.equal(normalizedPresetRow.slot, 'wrist')
  assert.equal(normalizedPresetRow.simcReady, true)

  const rows = helpers.filterLootRows(
    [
      { instanceId: 'a', encounterId: 'boss-1', name: 'Gaze of the Alnseer', encounterName: 'Chimaerus' },
      { instanceId: 'b', encounterId: 'boss-2', name: 'Skybreaker Blade', encounterName: 'Zuraal' }
    ],
    { instanceId: 'a', q: 'gaze' }
  )

  assert.equal(rows.length, 1)
  assert.equal(rows[0].encounterName, 'Chimaerus')
})

test('websim build helpers encode pvp slots without losing slot order', () => {
  const helpers = require('../websim/app')
  const encoded = helpers.encodePvpBuildSelections([
    'deathknight:blood:mind freeze',
    '',
    'deathknight:blood:anti-magic zone'
  ])

  assert.equal(encoded, 'deathknight%3Ablood%3Amind%20freeze,,deathknight%3Ablood%3Aanti-magic%20zone')
  assert.deepEqual(helpers.decodePvpBuildSelections(encoded), [
    'deathknight:blood:mind freeze',
    '',
    'deathknight:blood:anti-magic zone'
  ])
  assert.deepEqual(helpers.decodePvpBuildSelections('bad%zz'), ['bad%zz', '', ''])
})
