export default defineAppConfig({
  pages: [
    'pages/news/news',
    'pages/news/list',
    'pages/news/detail',
    'pages/builds/builds',
    'pages/builds/workbench',
    'pages/builds/intel',
    'pages/builds/talent-simulator',
    'pages/builds/detail',
    'pages/simulator/simulator',
    'pages/simulator/simc',
    'pages/simulator/chickenbro',
    'pages/simulator/tasks',
    'pages/simulator/task-detail',
    'pages/profile/profile',
    'pages/auth/web-login-confirm',
  ],
  window: {
    backgroundColor: '#080908',
    backgroundTextStyle: 'light',
    navigationBarTextStyle: 'white',
    navigationStyle: 'custom',
  },
  tabBar: {
    custom: true,
    color: '#766f61',
    selectedColor: '#e7b93d',
    backgroundColor: '#0e0c09',
    borderStyle: 'black',
    list: [
      { pagePath: 'pages/news/news', text: '资讯' },
      { pagePath: 'pages/builds/builds', text: '专精' },
      { pagePath: 'pages/simulator/simulator', text: '队长' },
      { pagePath: 'pages/profile/profile', text: '我的' },
    ],
  },
  style: 'v2',
  lazyCodeLoading: 'requiredComponents',
})
