GRANT USAGE ON SCHEMA identity, app, content, cache, knowledge, analytics, ops TO wow_migrator;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA identity, app, content, cache, knowledge, analytics, ops
TO wow_migrator;

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA identity, app, content, cache, knowledge, analytics, ops
TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA identity
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA app
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA content
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA cache
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA knowledge
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA analytics
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ops
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA identity
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA app
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA content
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA cache
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA knowledge
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA analytics
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO wow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ops
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO wow_migrator;

INSERT INTO ops.schema_migrations (id, description)
VALUES (
    '0009_runtime_reconcile_privileges',
    'Grant PostgreSQL reconciliation privileges to wow_migrator'
)
ON CONFLICT (id) DO UPDATE
SET description = EXCLUDED.description,
    applied_at = now();
